#!/usr/bin/env python3
"""Macros for what the overflow fallback contributes, from the three RULER arms.

The review asks how much of the RULER accuracy is sustained by the dense
fallback rather than by the sparse trigger. Three arms answer it, matched on
seed, prompt count, lengths and tasks, differing in one flag and one env var:

    fbablate-on     the deployed algorithm; nothing set
    fbablate-off    SGLANG_DEBUG_VESTIGEKV_NO_OVERFLOW_FALLBACK=1

Both are the same VestigeKV arm on the same tree at seed 0, differing in that
one key. Deleting the fallback is not a configuration this paper deploys: the
release branch exposes no switch for it, and what the deleted arm runs is an
incomplete algorithm.

All three are re-run by mexp/exp/ruler-fallback-ablation.sh rather than
assembled from what was on disk. The earlier no-fallback pair went through a
server flag that the release branch no longer has, and their only candidate
control was untagged, with no surviving queue entry naming its tree or flags;
pairing a matched pair with an unprovenanced third arm is the defect that
cost this paper its RoPE table.

What the numbers are for. Deleting the fallback is an ablation, not a cheaper
configuration -- the admission rule is uncapped and the buffer is a graph
width, so an overflow is the certificate reporting that a step cannot be
served sparsely at the recall target. These macros measure what answering that
report is worth, which is why the paper prints them next to the overflow rate.

Cells are 50 prompts wide -- the same depth as the RULER table the result is
printed beside -- and the paired count across all nine is still what the
comparison rests on, not any single cell.

    python mexp/kimi/make_fallback_numbers.py [--out ~/vestigekv_paper/fallback_numbers.tex]
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RULER = os.path.join(ROOT, "results", "kimi", "ruler")
STEM = "results_vestigekv_n50_16384-32768-65536_%s.json"
# The queue is what ran, and its ids are the tags on disk. The prereg script
# named its arms fb-on / fb-off-prefix; the registered jobs are fbablate-on /
# fbablate-off, and a reducer that looks for the script's names while the
# queue writes its own finds nothing and says so -- which is what happened,
# and is better than the alternative this file warns about two lines down.
ARMS = [("fbablate-on", "On"), ("fbablate-off", "Prefix")]
LENGTHS = ("16384", "32768", "65536")


def cells(tag):
    """{(task, length): score} for one arm, dropping lm-eval's -1 not-run cells."""
    path = os.path.join(RULER, STEM % tag)
    if not os.path.exists(path):
        raise SystemExit(
            f"missing arm: {path}\n"
            "All three arms come from mexp/exp/ruler-fallback-ablation.sh. Do "
            "NOT substitute the older trunc-*-nofb records or the untagged "
            "file: those went through a server flag the release branch no "
            "longer has, and the untagged one names no tree at all.")
    d = json.load(open(path))
    out = {}
    for task, row in d["results"].items():
        for k, v in row.items():
            # A length the job did not run is written "N/A", not -1, and a
            # filter that knows only about -1 turns the first such cell into a
            # crash. Both spellings mean the same thing: no measurement here.
            if not str(k).endswith(",none") or v == -1 or not isinstance(v, (int, float)):
                continue
            out[(task, str(k).split(",")[0])] = float(v)
    return out, d.get("n_per_cell"), d.get("seed")


def sign_test_p(down, total):
    """Two-sided exact sign test over the cells that moved at all."""
    if total == 0:
        return 1.0
    tail = sum(math.comb(total, k) for k in range(down, total + 1)) / 2 ** total
    return min(1.0, 2 * tail)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/fallback_numbers.tex"))
    args = ap.parse_args()

    arms = {name: cells(tag) for tag, name in ARMS}
    on, n_per_cell, seed = arms["On"]
    # Intersect whatever arms were registered. The third arm (spread
    # truncation) is not among them: the release branch reaches the truncation
    # policy through no switch at all, so the deletion this paper measures is
    # the one key it does expose.
    keys = sorted(set.intersection(*(set(arms[n][0]) for _, n in ARMS)))
    if not keys:
        raise SystemExit("the arms share no cell; check the tasks/lengths")

    L = ["% Generated by mexp/kimi/make_fallback_numbers.py from results/kimi/ruler/. "
         "Do not edit by hand.",
         f"\\newcommand{{\\fbCells}}{{{len(keys)}}}",
         f"\\newcommand{{\\fbPerCell}}{{{n_per_cell}}}"]
    for name, _ in ((n, t) for t, n in ARMS):
        vals = [arms[name][0][k] for k in keys]
        L.append(f"\\newcommand{{\\fbMean{name}}}{{{sum(vals) / len(vals):.2f}}}")
    for name in [n for _, n in ARMS if n != "On"]:
        off = arms[name][0]
        down = sum(off[k] < on[k] for k in keys)
        up = sum(off[k] > on[k] for k in keys)
        L.append(f"\\newcommand{{\\fbDown{name}}}{{{down}}}")
        L.append(f"\\newcommand{{\\fbUp{name}}}{{{up}}}")
        L.append(f"\\newcommand{{\\fbP{name}}}"
                 f"{{{sign_test_p(down, down + up):.3f}}}")
    # the single widest cell, named, so the worst case is not hidden by a mean
    worst = max(keys, key=lambda k: on[k] - arms["Prefix"][0][k])
    L.append(f"\\newcommand{{\\fbWorstTask}}{{\\texttt{{{worst[0].replace('_', chr(92) + '_')}}}}}")
    L.append(f"\\newcommand{{\\fbWorstLen}}{{{int(worst[1]) // 1024}k}}")
    L.append(f"\\newcommand{{\\fbWorstOn}}{{{on[worst]:.2f}}}")
    L.append(f"\\newcommand{{\\fbWorstPrefix}}{{{arms['Prefix'][0][worst]:.2f}}}")

    # The other end of the range: the same deletion on a 128k stream, where
    # the paper quotes a per-token cost. Hand-typing it into the prose is how
    # 5.444 and 5.426 came to sit in a sentence beside macros.
    import json as _json
    R = os.path.join(ROOT, "results", "kimi")
    pair = {"On": "latency_stream_4k-126976_vestigekv_stats.jsonl",
            "Prefix": "latency_stream_4k-126976_vestigekv_stats_fbstream-off.jsonl"}
    itl = {}
    for name, f in pair.items():
        path = os.path.join(R, f)
        if os.path.exists(path):
            itl[name] = float(_json.loads(open(path).read().splitlines()[0])["mean_itl_ms"])
    if len(itl) == 2:
        L.append(f"\\newcommand{{\\fbStreamOn}}{{{itl['On']:.3f}}}")
        L.append(f"\\newcommand{{\\fbStreamPrefix}}{{{itl['Prefix']:.3f}}}")
        L.append(f"\\newcommand{{\\fbStreamDelta}}"
                 f"{{{abs(itl['Prefix'] - itl['On']) / itl['On'] * 100:.1f}\\%}}")

    # The buffer's capacity, read from the backend's own defaults rather than
    # typed into a sentence. The appendix argues that a fetch distribution
    # whose upper decile stands AT capacity is what an overflow is, and that
    # argument is only checkable if the two numbers come from one place.
    # It is a server argument, not a module constant, so read it from the run
    # that produced these records -- the backend logs its resolved config.
    import re as _re
    for f in ("server_vestigekv_statsruler64-vestigekv.log",
              "server_vestigekv_fbablate-on.log"):
        path = os.path.join(ROOT, "results", "kimi", f)
        if not os.path.exists(path):
            continue
        m = _re.search(r"recall_capacity=(\d+)", open(path, errors="replace").read(200000))
        if m:
            L.append(f"\\newcommand{{\\fbCapacity}}{{{m.group(1)}}}")
            break
    else:
        raise SystemExit("ABORT: no run log names recall_capacity")

    # "fourteen-step answers" carries the whole mechanism and appeared three
    # times as a written-out word. It is steps/requests from the stats run.
    import glob as _glob
    g = _glob.glob(os.path.join(ROOT, "results", "kimi", "ruler",
                                "results_vestigekv_n10_65536_statsruler64*.json"))
    st = _glob.glob(os.path.join(ROOT, "results", "kimi",
                                 "server_vestigekv_statsruler64-vestigekv.log"))
    if g and st:
        d = json.load(open(g[0]))
        reqs = len(d["results"]) * d.get("n_per_cell", 10)
        # the LAST line: the counter is cumulative, and the first one reads 0
        hits = _re.findall(r"VKSTATS steps=(\d+)",
                           open(st[0], errors="replace").read())
        if hits and int(hits[-1]):
            L.append(f"\\newcommand{{\\fbAnswerSteps}}{{{round(int(hits[-1]) / reqs)}}}")

    open(args.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {args.out}: {len(L) - 1} macros over {len(keys)} shared cells "
          f"(n={n_per_cell} per cell, seed {seed})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
