#!/usr/bin/env python3
"""Figure 2's right panel, reduced from the tput32 sweep.

    python mexp/kimi/make_throughput_numbers.py --emit
    python mexp/kimi/make_throughput_numbers.py --check   # exit 1 on a mismatch

WHY THIS EXISTS AS A CHECK AND NOT ONLY A GENERATOR. The caption already
states the sweep's configuration -- radix cache off on both arms, every point
served by a graph captured at bs=32 -- while serving_numbers.tex still holds
the previous sweep's values, taken with the radix cache on and at a capture
width no surviving record names. A caption describing one run above numbers
from another is the exact failure that cost this paper its RoPE table, and it
is invisible to every other check we have: the macros are defined, the paper
compiles, the figure renders.

So this refuses. Until the tput32 records exist, --check fails and says the
caption is ahead of its data; once they exist, --emit replaces the macros and
--check holds them to the records from then on. Run --check before submitting.
"""
from __future__ import annotations

import argparse
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESULTS = os.path.join(ROOT, "results", "kimi")
PAPER = os.path.expanduser("~/vestigekv_paper")
OUT = os.path.join(PAPER, "serving_numbers.tex")

# The full grid the previous sweep used. The first draft of this script took a
# subset -- 1, 4, 12, 24, 32 -- for no recorded reason, and the point it left
# out was bs=16, which is exactly where the old records claimed the peak 1.14x.
# A grid that skips the comparison's strongest point is not a re-measurement.
BATCHES = [1, 2, 4, 8, 12, 16, 24, 32]
WORD = {1: "One", 2: "Two", 4: "Four", 8: "Eight", 12: "Twelve", 16: "Sixteen",
        24: "TwentyFour", 32: "ThirtyTwo"}


def record(bs, arm):
    """The client JSONL the runner writes for tput32-bs<N>-<arm>."""
    shape = f"64k-4096" + (f"-x{bs}" if bs > 1 else "") + (f"-c{bs}" if bs > 1 else "")
    return os.path.join(RESULTS, f"latency_stream_{shape}_{arm}.jsonl")


def throughput(path, bs):
    """Decoded tokens per second, prefill excluded.

    The client's own `output_throughput` divides the decoded tokens by the
    whole benchmark, prefill included -- 8.4 of the 26.4 seconds at bs=1, a
    third of the wall clock -- and this paper does not count prefill. It also
    dilutes in the one direction that matters: prefill is where VestigeKV is
    slightly SLOWER, paying to build its index, so the diluted figure reports
    1.030x at bs=1 where the decode is 1.050x, which is what the latency curve
    independently measures at the same context.

    With every request submitted at once, the batch decodes together and the
    steady-state rate is bs / mean_itl. Checked against the residual
    duration - ttft below, because a mean ITL that quietly included the
    prefill step would reproduce the very error this replaces."""
    blob = json.loads(open(path).read())
    itl = float(blob["mean_itl_ms"]) / 1000.0
    n_out, dur = int(blob["total_output_tokens"]), float(blob["duration"])
    residual = dur - float(blob["mean_ttft_ms"]) / 1000.0
    implied = (n_out / bs) * itl
    if abs(implied - residual) > 0.1 * residual:
        raise SystemExit(
            f"ABORT: {os.path.basename(path)} decode time from ITL ({implied:.1f}s) "
            f"and from duration-TTFT ({residual:.1f}s) disagree by more than 10%; "
            "one of them is not measuring the decode")
    return bs / itl


def survey():
    have, missing = {}, []
    for bs in BATCHES:
        pair = {}
        for arm in ("baseline", "vestigekv"):
            p = record(bs, arm)
            if os.path.exists(p):
                pair[arm] = throughput(p, bs)
            else:
                missing.append(os.path.relpath(p, ROOT))
        if len(pair) == 2:
            have[bs] = pair
    return have, missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    have, missing = survey()
    for bs in sorted(have):
        d, v = have[bs]["baseline"], have[bs]["vestigekv"]
        print(f"  bs={bs:<3} dense {d:>8.1f}  vk {v:>8.1f}  {v / d:.3f}x")

    if missing:
        msg = ("the caption says the sweep is radix-off with graphs captured at "
               "bs=32, and these records do not exist yet:\n  "
               + "\n  ".join(missing)
               + "\nRun the registered tput32 jobs (README.md) before submitting.")
        if a.check or a.emit:
            raise SystemExit("ABORT: " + msg)
        print("PENDING: " + msg)
        return 0

    lines = ["% Generated by mexp/kimi/make_throughput_numbers.py from the tput32",
             "% sweep: 64k prefill + 4096 decoded tokens, radix cache off on both",
             "% arms, GRAPH_BS=32=MAX_REQS at every point.",
             "% Decoded tokens per second with prefill excluded (bs / mean ITL);",
             "% ratios are vestigekv/dense."]
    for bs in sorted(have):
        d, v = have[bs]["baseline"], have[bs]["vestigekv"]
        lines.append(f"\\newcommand{{\\srvBatch{WORD[bs]}}}{{{v / d:.2f}}}"
                     f"  % bs={bs}: {v:.1f}/{d:.1f} tok/s")
    gain = have[12]["vestigekv"] / have[12]["baseline"] - 1
    lines.append(f"\\newcommand{{\\tputGainTwelve}}{{{gain * 100:.1f}\\%}}")
    lines.append("\\newcommand{\\srvBatchList}{"
                 + ", ".join(f"${have[b]['vestigekv'] / have[b]['baseline']:.2f}\\times$"
                             for b in sorted(have)) + "}")

    if a.check:
        cur = open(OUT).read()
        for line in lines:
            name = re.match(r"\\newcommand\{\\(\w+)\}", line)
            if name and line.split("%")[0].strip() not in cur:
                raise SystemExit(
                    f"ABORT: the paper's \\{name.group(1)} does not match the "
                    "sweep on disk. Re-run with --emit.")
        print("check: the throughput macros match the records")
    if a.emit:
        open(OUT, "w").write("\n".join(lines) + "\n")
        print(f"wrote {OUT}")
        # numbers.tex carries a hand-maintained \tputGainTwelve from the retired
        # sweep. Two \newcommand of one name is not a stale value, it is a
        # build failure -- and it would have arrived the moment this script
        # first succeeded, which is the moment nobody is looking for one.
        nums = os.path.join(PAPER, "numbers.tex")
        text = open(nums).read()
        kept = [l for l in text.splitlines()
                if not re.match(r"\\newcommand\{\\tputGainTwelve\}", l.strip())]
        if len(kept) != len(text.splitlines()):
            open(nums, "w").write("\n".join(kept) + "\n")
            print(f"removed the hand-maintained \\tputGainTwelve from numbers.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
