#!/usr/bin/env python3
"""Macros for the tier-1 necessity ablation.

    python mexp/kimi/make_tier1_numbers.py [--out ~/vestigekv_paper/tier1_numbers.tex]

The shipped ablation deletes tier 2 and shows tier 1 alone is not enough. That
is a different claim from "tier 1 has to be sigma", and only the second one
supports reading the decoupled branch as the thing the method rests on. Tier 2
scans every archived row whatever tier 1 kept, so the question is whether the
certificate recovers the needles over a selector that carries no salience at
all.

Five selectors, both tiers on, the protocol of the retrieval table: 24 trials
at L=8192, seed 0, Instruct. sigma is the deployed one and is the control; it
has to reproduce that table's cells or nothing beside it is comparable.
A random draw is the strongest of the alternatives to report, because a
selector that cannot be carrying information is the one whose result cannot be
explained away.
"""
from __future__ import annotations

import argparse
import collections
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RECORD = "results/harness_tier1_8192.json"
# op -> macro infix. The deployed selector keeps the plain name.
OPS = {"twotier": "Sigma", "twotier_stride": "Stride", "twotier_norm": "Norm",
       "twotier_recent": "Recent", "twotier_random": "Random"}
RATIO = {32: "ThirtyTwo", 128: "OTE"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/tier1_numbers.tex"))
    a = ap.parse_args()

    p = os.path.join(ROOT, RECORD)
    if not os.path.exists(p):
        raise SystemExit(f"ABORT: {RECORD} is not on disk")
    d = json.load(open(p))
    agg = collections.defaultdict(list)
    base = {}
    for r in d["rows"]:
        if r.get("kind") != "needle":
            continue
        agg[(round(1 / r["rho"]), r["op"])].append(r["d"])
        # Every selector must have answered the same needles, or the cells are
        # five different questions. The dense forward's NLL per trial is the
        # fingerprint: bit-identical iff the prompt is.
        base.setdefault(r["op"], {}).setdefault(r["trial"], r["base"])
    ref = "twotier"
    for op in sorted(base):
        if op == ref:
            continue
        bad = [t for t in base[ref] if base[op].get(t) != base[ref][t]]
        if bad:
            raise SystemExit(
                f"ABORT: {op} and {ref} disagree on the dense baseline of "
                f"{len(bad)} trials, so they did not see the same needles.")
    print(f"control check: {len(base)} selectors agree on the dense baseline "
          f"of all {len(base[ref])} trials")

    L = ["% Generated by mexp/kimi/make_tier1_numbers.py from results/. "
         "Do not edit by hand."]
    ns = set()
    for (ratio, op), v in sorted(agg.items()):
        if ratio not in RATIO or op not in OPS:
            continue
        ns.add(len(v))
        L.append(f"\\newcommand{{\\tierOne{OPS[op]}{RATIO[ratio]}}}"
                 f"{{{sum(x < 1 for x in v) / len(v):.2f}}}")
    if len(ns) == 1:
        L.append(f"\\newcommand{{\\tierOneTrials}}{{{ns.pop()}}}")
    L.append(f"\\newcommand{{\\tierOneArms}}{{{len(OPS)}}}")
    # One number for the body: how many of the reported cells move at all.
    cells = [(r, o) for (r, o) in agg if r in RATIO and o in OPS]
    ref_rate = {r: sum(x < 1 for x in agg[(r, ref)]) / len(agg[(r, ref)]) for r in RATIO}
    moved = sum(1 for (r, o) in cells if o != ref
                and abs(sum(x < 1 for x in agg[(r, o)]) / len(agg[(r, o)]) - ref_rate[r]) > 1e-9)
    L.append(f"\\newcommand{{\\tierOneMoved}}{{{moved}}}")
    L.append(f"\\newcommand{{\\tierOneCells}}{{{len(cells) - len(RATIO)}}}")

    # Telemetry, at the deployed ratio. The needle cells cannot separate the
    # selectors because the certificate recovers every trial whatever tier 1
    # kept; these two can, and they are the mechanism. sound_rate is the share
    # of (query, head) for which SOME archived row beats the kept tier's
    # maximum under the sound Cauchy-Schwarz bound: at exactly 1.000 the
    # admission test excludes nothing. conf_rec is the recall the calibrated z
    # achieves, and a selector that lands far above the 0.90 target is one
    # whose threshold was too low to be selective.
    import statistics
    trig = [t for t in d.get("trigger", []) if round(1 / t["rho"]) == 32]
    for op, infix in OPS.items():
        v = [t for t in trig if t.get("op") == op]
        sr = [t["sound_rate"] for t in v if t.get("sound_rate") is not None]
        cr = [t["conf_rec"] for t in v if t.get("conf_rec") is not None]
        if sr:
            L.append(f"\\newcommand{{\\tierOne{infix}Sound}}"
                     f"{{{statistics.median(sr):.3f}}}")
        if cr:
            L.append(f"\\newcommand{{\\tierOne{infix}Rec}}"
                     f"{{{statistics.median(cr):.3f}}}")
    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out}: {len(L) - 1} macros; "
          f"{moved} of {len(cells) - len(RATIO)} alternative cells differ from sigma")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
