#!/usr/bin/env python3
"""Compare selecting on the vestige branch against selecting on the whole row.

The paper's thesis is that the 64-dim decoupled branch carries the cache's
salience signal, so selection can read 11% of each row instead of all of it.
The control for that is `full-row eviction` -- the identical policy scoring on
the full 576-dim latent -- and the two were measured on the same grid of
(context length, compression ratio) operating points.

Nine points exist. The paper cited one of them, in the RoPE control table,
which is the point where the branch happens to win; the other eight were
measured and never reached the prose. That is the wrong way round: the
interesting result is not that the branch wins somewhere, it is that reading a
ninth of the row is not a lossy proxy for reading all of it ANYWHERE on the
grid. This emits that comparison as macros so the body can state it in one
sentence and a re-run cannot silently invalidate it.

Source of record is `numbers.tex`. That file is hand-maintained (its own header
says so, and the generator that once wrote it is gone), and these nine values
each carry the run record they came from in a trailing comment. Reading it here
rather than re-deriving from results/ keeps one copy of the numbers: if a value
is corrected there, this follows.

    python mexp/kimi/make_selector_numbers.py [--out ~/vestigekv_paper/selector_numbers.tex]
"""
from __future__ import annotations

import argparse
import os
import re
import sys

# (macro suffix, context label, ratio label) -- the grid both selectors ran on.
GRID = [("EightKxThirtyTwo", "8k", "32x"),
        ("EightKxSixtyFour", "8k", "64x"),
        ("EightKxOTE", "8k", "128x"),
        ("ThirtyTwoKxThirtyTwo", "32k", "32x"),
        ("ThirtyTwoKxSixtyFour", "32k", "64x"),
        ("ThirtyTwoKxOTE", "32k", "128x"),
        ("SixtyFiveKxThirtyTwo", "65k", "32x"),
        ("SixtyFiveKxSixtyFour", "65k", "64x"),
        ("SixtyFiveKxOTE", "65k", "128x")]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--numbers", default=os.path.expanduser(
        "~/vestigekv_paper/numbers.tex"))
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/selector_numbers.tex"))
    ap.add_argument("--show", action="store_true", help="print the grid")
    args = ap.parse_args()

    d = dict(re.findall(r"\\newcommand\{\\(\w+)\}\{([^}]*)\}",
                        open(args.numbers).read()))
    same = vk_win = full_win = 0
    gap = 0.0
    rows = []
    for suf, ctx, ratio in GRID:
        a, b = d.get("vk" + suf), d.get("full" + suf)
        if a is None or b is None:
            # A missing pair means the grid changed; refuse rather than emit a
            # count over a different set of points than the sentence claims.
            print(f"missing pair for {suf}: vk={a} full={b}", file=sys.stderr)
            return 1
        a, b = float(a), float(b)
        same += a == b
        vk_win += a > b
        full_win += a < b
        gap = max(gap, a - b)
        rows.append((ctx, ratio, a, b))

    if args.show:
        for ctx, ratio, a, b in rows:
            print(f"  {ctx:>4} {ratio:>5}  branch {a:.2f}  full-row {b:.2f}")

    L = ["% Generated by mexp/kimi/make_selector_numbers.py from numbers.tex. "
         "Do not edit by hand.",
         f"\\newcommand{{\\selPoints}}{{{len(GRID)}}}",
         f"\\newcommand{{\\selSame}}{{{same}}}",
         f"\\newcommand{{\\selBranchBetter}}{{{vk_win}}}",
         f"\\newcommand{{\\selFullBetter}}{{{full_win}}}",
         f"\\newcommand{{\\selMaxGap}}{{{gap:.2f}}}"]
    open(args.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {args.out}: {len(GRID)} points, "
          f"same={same} branch={vk_win} full={full_win}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
