#!/usr/bin/env python3
"""The sidecar-spectrum macros: what the synthetic haystack puts in sigma.

    python mexp/kimi/make_spectrum_numbers.py --emit

Appendix F reports that RULER's sidecar carries a standing component above the
low-pass cutoff, and that notching it moves a large share of tier 1's kept
set. That claim is only publishable WITH its contrast -- real prose does not
carry it -- because the RULER half alone reads as a defect in the method
rather than a property of the benchmark. So the emitted macros are PENDING
until both halves have enough requests to be a property rather than a sample,
and the paper shows PENDING rather than half the story.

MIN_REQUESTS is 3 per condition. RULER reached five by accident: its prompts
differ in length by a few dozen tokens, and the dump's filename carries the
sequence length, so they did not collide. The prose dumps run at 64k, 62k,
60k and 58k for that reason and not because length is interesting.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import statistics
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESULTS = os.path.join(ROOT, "results", "kimi")
OUT = os.path.expanduser("~/vestigekv_paper/spectrum_numbers.tex")
sys.path.insert(0, os.path.join(ROOT, "engine", "python"))
from sglang.srt.layers.attention.vestigekv import defaults as _D  # noqa: E402

KAPPA, BLOCK, MIN_REQUESTS = _D.LOWPASS_KAPPA, _D.CLOSE_BLOCK, 3
LAYER = 19  # one layer read across requests; all seven agree (SIDECAR_SPECTRUM.md)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def measure(dump):
    """[(peak bin, peakiness, top-3% of the kept set surviving a notch)]."""
    import torch
    from sidecar_spectrum_offline import load, spectrum

    out = []
    for path in sorted(glob.glob(os.path.join(dump, f"cal_tp0_*lid{LAYER}_*.pt"))):
        _, side = load(path)
        energy = spectrum(side, KAPPA, BLOCK)
        above = energy[KAPPA:]
        bins = [int(b) for b in (torch.topk(above, 6).indices + KAPPA)]
        seg = side[:BLOCK]

        def sigma(notch=()):
            f = torch.fft.rfft(seg, dim=0)
            g = f.clone()
            g[KAPPA:] = 0
            for b in notch:
                g[b] = f[b]
            return (seg - torch.fft.irfft(g, n=BLOCK, dim=0)).pow(2).sum(1).sqrt()

        m = int(BLOCK * 0.03)
        kept = len(set(torch.topk(sigma(), m).indices.tolist())
                   & set(torch.topk(sigma(tuple(bins)), m).indices.tolist())) / m
        out.append((int(above.argmax()) + KAPPA,
                    float(above.max() / above.median()), kept))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    a = ap.parse_args()

    conds = {"Ruler": ["sidecardump", "sidecardump5"],
             "Prose": ["sidecardump_prose", "sidecardump_prose5"]}
    got = {}
    for mac, dirs in conds.items():
        rows = [r for d in dirs for r in measure(os.path.join(RESULTS, d))]
        got[mac] = rows
        print(f"  {mac:6} {len(rows)} requests"
              + (f"   bins {sorted({b for b, _, _ in rows})}"
                 f"   peakiness {min(p for _, p, _ in rows):.0f}-{max(p for _, p, _ in rows):.0f}"
                 f"   kept {min(k for _, _, k in rows):.1%}-{max(k for _, _, k in rows):.1%}"
                 if rows else "   (none)"))

    short = [m for m, r in got.items() if len(r) < MIN_REQUESTS]
    lines = ["% Generated by mexp/kimi/make_spectrum_numbers.py from the sidecar dumps.",
             f"% Layer {LAYER}; all seven agree. Kappa {KAPPA}, block {BLOCK}.",
             # the block width is CLOSE_BLOCK in the backend, so the prose says
             # what the code fixes rather than a number typed beside it
             f"\\newcommand{{\\blockRows}}{{{BLOCK}}}"]
    if short:
        print(f"  PENDING: {short} under {MIN_REQUESTS} requests; the contrast is "
              "the claim, and half of it is not publishable on its own")
        for mac in conds:
            for k in ("Bin", "Peak", "Kept", "N"):
                lines.append(f"\\newcommand{{\\spec{mac}{k}}}{{\\PENDING}}")
    else:
        for mac, rows in got.items():
            bins = sorted({b for b, _, _ in rows})
            lines.append(f"\\newcommand{{\\spec{mac}Bin}}"
                         f"{{{bins[0] if len(bins) == 1 else f'{bins[0]}--{bins[-1]}'}}}")
            lines.append(f"\\newcommand{{\\spec{mac}Peak}}"
                         f"{{{statistics.fmean(p for _, p, _ in rows):.0f}}}")
            lines.append(f"\\newcommand{{\\spec{mac}Kept}}"
                         f"{{{statistics.fmean(k for _, _, k in rows) * 100:.0f}\\%}}")
            lines.append(f"\\newcommand{{\\spec{mac}N}}{{{len(rows)}}}")
    if a.emit:
        open(OUT, "w").write("\n".join(lines) + "\n")
        print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
