#!/usr/bin/env python3
"""Macros for the oracle-overlap evidence that the tier-1 signal is a property
of natural text.

    python mexp/kimi/make_notch_numbers.py [--out ~/vestigekv_paper/notch_numbers.tex]

The paper's claim is that what tier 1 selects on is structure real prose
carries and synthetic haystacks do not. Until now the body supported that with
the peak's PROMINENCE (724x the median bin under RULER against 91x under
prose). Our own notch study says that statistic does not separate the two
corpora: RULER's minimum over layers (50) sits below prose's maximum (93), so
a magnitude threshold has no margin. What separates them 70/70 is the peak's
LOCATION -- bin 71/72, the filler's own sentence cadence, against bin 16/17,
the shoulder any smooth signal leaves at the cutoff.

The stronger evidence in the same study is operational rather than spectral.
The calibration dumps carry each request's own absorbed decode queries, so the
rows those queries really score highest are computable: an oracle top-m at the
same 3% budget. Tier 1's overlap with that oracle is 3.3x the random baseline
on real prose and only 1.6x on RULER's haystack. That is the applicability
claim measured directly -- not "prose has a different spectrum" but "on prose
the query-independent selector actually points where the queries go, and on a
synthetic haystack it barely does".

PROVENANCE. This reduction is parsed from the archived study document rather
than recomputed, because the sidecar dumps behind it were deliberately not
retained: they were 10.42 GB, 98.6% of an archive whose every other file
totals 145 MB. The document and the script that produced it
(mexp/kimi/spectrum_notch_study.py) are both in the supplement, and the paper
says so where it quotes the numbers. The same is true of the spectrum macros
this sits next to, so it introduces no weaker provenance than the claim it
strengthens -- but it is a transcription, and the parser below fails loudly if
the document's tables stop having the shape it expects rather than emitting a
number no record backs.
"""
from __future__ import annotations

import argparse
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
STUDY = "docs/sidecar-notch-study.md"
ROW = re.compile(r"^\|\s*(RULER haystack|real prose)\s*\|(.+)\|\s*$", re.M)


def cells(line):
    return [c.strip() for c in line.split("|") if c.strip()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/notch_numbers.tex"))
    a = ap.parse_args()

    p = os.path.join(ROOT, STUDY)
    if not os.path.exists(p):
        raise SystemExit(f"ABORT: {STUDY} is not on disk")
    doc = open(p).read()

    # The oracle table is the second of the two the document carries; take it
    # by its heading so a reordering of the file cannot silently swap them.
    try:
        sec = doc[doc.index("## Notching sigma does not move it toward"):
                  doc.index("## What the same table says")]
    except ValueError:
        raise SystemExit("ABORT: the oracle-overlap section is not in the study")
    got = {}
    for m in ROW.finditer(sec):
        c = cells(m.group(2))
        if len(c) != 3:
            raise SystemExit(f"ABORT: oracle row for {m.group(1)!r} has "
                             f"{len(c)} columns, expected 3 "
                             f"(sigma, notched, random)")
        got[m.group(1)] = c
    if set(got) != {"RULER haystack", "real prose"}:
        raise SystemExit(f"ABORT: oracle table names {sorted(got)}, "
                         f"expected both corpora")

    def pct(x):
        return float(x.rstrip("%"))

    def tex(x):
        # a bare % opens a LaTeX comment and would swallow the closing brace
        return x.replace("%", "\\%")

    ruler, prose = got["RULER haystack"], got["real prose"]
    base = pct(prose[2])
    if pct(ruler[2]) != base:
        raise SystemExit("ABORT: the two corpora report different random "
                         "baselines, so their multiples are not comparable")

    L = ["% Generated by mexp/kimi/make_notch_numbers.py from "
         f"{STUDY}. Do not edit by hand.",
         f"% Transcribed from the archived study, not recomputed: the sidecar",
         f"% dumps behind it were not retained (10.42 GB, 98.6% of the archive)."]
    L.append(f"\\newcommand{{\\notchOracleProse}}{{{tex(prose[0])}}}")
    L.append(f"\\newcommand{{\\notchOracleRuler}}{{{tex(ruler[0])}}}")
    L.append(f"\\newcommand{{\\notchOracleFloor}}{{{tex(prose[2])}}}")
    L.append(f"\\newcommand{{\\notchOracleProseX}}"
             f"{{{pct(prose[0]) / base:.1f}$\\times$}}")
    L.append(f"\\newcommand{{\\notchOracleRulerX}}"
             f"{{{pct(ruler[0]) / base:.1f}$\\times$}}")

    # the location-vs-prominence correction, from the first table
    m = re.search(r"snapshots per corpus", doc)
    n = re.search(r"(\d+) \(request, layer\) snapshots per corpus", doc)
    if not n:
        raise SystemExit("ABORT: the study does not state its snapshot count")
    L.append(f"\\newcommand{{\\notchSnaps}}{{{n.group(1)}}}")

    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out}: {sum(1 for x in L if x.startswith(chr(92)))} macros")
    print(f"   sigma vs oracle: prose {prose[0]} ({pct(prose[0]) / base:.1f}x "
          f"random), RULER {ruler[0]} ({pct(ruler[0]) / base:.1f}x), "
          f"floor {prose[2]}, over {n.group(1)} snapshots per corpus")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
