#!/usr/bin/env python3
"""Macros for what the overflow fallback contributes, from the three RULER arms.

The review asks how much of the RULER accuracy is sustained by the dense
fallback rather than by the sparse trigger. Three arms answer it, matched on
seed, prompt count, lengths and tasks, differing in one flag and one env var:

    fb-on           the deployed algorithm; nothing set
    fb-off-prefix   SGLANG_DEBUG_VESTIGEKV_NO_OVERFLOW_FALLBACK=1
    fb-off-spread   the same, plus SGLANG_DEBUG_VESTIGEKV_SPREAD_TRUNCATE=1

All three are re-run by mexp/exp/ruler-fallback-ablation.sh rather than
assembled from what was on disk. The earlier no-fallback pair went through a
server flag that the release branch no longer has, and their only candidate
control was untagged, with no surviving queue entry naming its tree or flags;
pairing a matched pair with an unprovenanced third arm is the defect that
cost this paper its RoPE table.

What the numbers are for. Deleting the fallback is an ablation, not a cheaper
configuration -- the admission rule is uncapped and the buffer is a graph
width, so an overflow is the certificate reporting that a step cannot be
served sparsely at the recall target. These macros measure what answering that
report is worth, which is why the paper prints them next to the overflow rate.

Cells are 10 prompts wide, so a single cell moves by 0.1 at a time and no cell
is evidence by itself. The paired count across all nine is.

    python mexp/kimi/make_fallback_numbers.py [--out ~/vestigekv_paper/fallback_numbers.tex]
"""
from __future__ import annotations

import argparse
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RULER = os.path.join(ROOT, "results", "kimi", "ruler")
STEM = "results_vestigekv_n10_16384-32768-65536_%s.json"
ARMS = [("fb-on", "On"), ("fb-off-prefix", "Prefix"), ("fb-off-spread", "Spread")]
LENGTHS = ("16384", "32768", "65536")


def cells(tag):
    """{(task, length): score} for one arm, dropping lm-eval's -1 not-run cells."""
    path = os.path.join(RULER, STEM % tag)
    if not os.path.exists(path):
        raise SystemExit(
            f"missing arm: {path}\n"
            "All three arms come from mexp/exp/ruler-fallback-ablation.sh. Do "
            "NOT substitute the older trunc-*-nofb records or the untagged "
            "file: those went through a server flag the release branch no "
            "longer has, and the untagged one names no tree at all.")
    d = json.load(open(path))
    out = {}
    for task, row in d["results"].items():
        for k, v in row.items():
            if str(k).endswith(",none") and v != -1:
                out[(task, str(k).split(",")[0])] = float(v)
    return out, d.get("n_per_cell"), d.get("seed")


def sign_test_p(down, total):
    """Two-sided exact sign test over the cells that moved at all."""
    if total == 0:
        return 1.0
    tail = sum(math.comb(total, k) for k in range(down, total + 1)) / 2 ** total
    return min(1.0, 2 * tail)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/fallback_numbers.tex"))
    args = ap.parse_args()

    arms = {name: cells(tag) for tag, name in ARMS}
    on, n_per_cell, seed = arms["On"]
    keys = sorted(set(on) & set(arms["Prefix"][0]) & set(arms["Spread"][0]))
    if not keys:
        raise SystemExit("the three arms share no cell; check the tasks/lengths")

    L = ["% Generated by mexp/kimi/make_fallback_numbers.py from results/kimi/ruler/. "
         "Do not edit by hand.",
         f"\\newcommand{{\\fbCells}}{{{len(keys)}}}",
         f"\\newcommand{{\\fbPerCell}}{{{n_per_cell}}}"]
    for name, _ in ((n, t) for t, n in ARMS):
        vals = [arms[name][0][k] for k in keys]
        L.append(f"\\newcommand{{\\fbMean{name}}}{{{sum(vals) / len(vals):.2f}}}")
    for name in ("Prefix", "Spread"):
        off = arms[name][0]
        down = sum(off[k] < on[k] for k in keys)
        up = sum(off[k] > on[k] for k in keys)
        L.append(f"\\newcommand{{\\fbDown{name}}}{{{down}}}")
        L.append(f"\\newcommand{{\\fbUp{name}}}{{{up}}}")
        L.append(f"\\newcommand{{\\fbP{name}}}"
                 f"{{{sign_test_p(down, down + up):.3f}}}")
    # the single widest cell, named, so the worst case is not hidden by a mean
    worst = max(keys, key=lambda k: on[k] - arms["Prefix"][0][k])
    L.append(f"\\newcommand{{\\fbWorstTask}}{{\\texttt{{{worst[0].replace('_', chr(92) + '_')}}}}}")
    L.append(f"\\newcommand{{\\fbWorstLen}}{{{int(worst[1]) // 1024}k}}")
    L.append(f"\\newcommand{{\\fbWorstOn}}{{{on[worst]:.2f}}}")
    L.append(f"\\newcommand{{\\fbWorstPrefix}}{{{arms['Prefix'][0][worst]:.2f}}}")
    L.append(f"\\newcommand{{\\fbWorstSpread}}{{{arms['Spread'][0][worst]:.2f}}}")

    open(args.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {args.out}: {len(L) - 1} macros over {len(keys)} shared cells "
          f"(n={n_per_cell} per cell, seed {seed})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
