#!/usr/bin/env python3
"""GSM8K-Platinum as counts, because a rate at this n cannot be inverted.

    python mexp/kimi/make_gsm8k_numbers.py --emit

The table reported 0.848 and its neighbours, three decimal places over 1209
questions. At that width one question is 0.083%, so a reader comparing two
arms cannot tell four questions from forty -- and the frozen bar is stated in
questions, within 2 sigma of dense. Worse, the rate is not invertible: 1107
and 1108 correct both print as 0.916, so the count is not recoverable from a
finished run's log at all. The harness prints `Correct: N / M` now and this
reads it.

The denominator is emitted once, for the caption, rather than repeated in
every cell.
"""
from __future__ import annotations

import argparse
import math
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESULTS = os.path.join(ROOT, "results", "kimi")
OUT = os.path.expanduser("~/vestigekv_paper/gsm8k_numbers.tex")
# The table's column names: `Base`/`Vk` are the dense and VestigeKV arms on
# the BASE checkpoint, the `I` suffix is the Instruct one. Both halves are
# measured here so the row does not mix counts with rates.
ARMS = {("baseline", "BaseI"): "gsm8kcount-baseline",
        ("vestigekv", "VkI"): "gsm8kcount-vestigekv",
        ("baseline", "Base"): "gsm8kcountbase-baseline",
        ("vestigekv", "Vk"): "gsm8kcountbase-vestigekv"}
LINE = re.compile(r"Correct:\s*(\d+)\s*/\s*(\d+)")


def read(arm, job):
    path = os.path.join(RESULTS, f"gsm8k_{arm}_{job}.log")
    if not os.path.exists(path):
        return None
    hits = LINE.findall(open(path, errors="replace").read())
    if not hits:
        raise SystemExit(
            f"ABORT: {os.path.basename(path)} has no `Correct: N / M` line. It "
            "predates the harness change that prints one; a rate at this n is "
            "not invertible, so the count cannot be recovered from it.")
    return int(hits[-1][0]), int(hits[-1][1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    a = ap.parse_args()

    got = {}
    for (arm, mac), job in ARMS.items():
        r = read(arm, job)
        if r:
            got[mac] = r
    if not got:
        print("PENDING: no gsm8kcount run yet")
        return 0
    ns = {n for _, n in got.values()}
    if len(ns) != 1:
        raise SystemExit(f"ABORT: the arms answered different question counts: {ns}")
    n = ns.pop()

    lines = ["% Generated by mexp/kimi/make_gsm8k_numbers.py from",
             "% results/kimi/gsm8k_{baseline,vestigekv}_gsm8kcount-*.log.",
             "% Counts, not rates: at this n a rate to three places cannot be inverted.",
             f"\\newcommand{{\\gsmTotal}}{{{n}}}"]
    for mac, (c, _) in sorted(got.items()):
        lines.append(f"\\newcommand{{\\gsmN{mac}}}{{{c}}}  % {c / n:.4f}")
        print(f"  {mac:6} {c} / {n}   {c / n:.4f}")
    if {"BaseI", "VkI"} <= set(got):
        # The frozen bar is "within 2 sigma of dense", and sigma belongs to the
        # binomial on the dense arm's rate, not to anything in the table.
        d = got["BaseI"][0] / n
        sd = math.sqrt(d * (1 - d) / n) * n
        gap = got["BaseI"][0] - got["VkI"][0]
        lines.append(f"\\newcommand{{\\gsmGap}}{{{gap}}}")
        lines.append(f"\\newcommand{{\\gsmTwoSigma}}{{{2 * sd:.1f}}}")
        print(f"  gap {gap} questions against a 2-sigma band of {2 * sd:.1f}")

    # Repeat runs. The VestigeKV arm is not bit-reproducible at fixed seed and
    # the dense arm is (docs/nondeterminism.md), so the appendix states both --
    # and states them from measurement, because "dense repeats exactly" is a
    # claim about the harness that a reader should be able to see the evidence
    # for. PENDING until the repeat lands: an unmeasured spread must not print
    # as zero, which is the one value that would read as a stronger claim than
    # the data supports.
    rep = {mac: read(arm, job)
           for (arm, mac), job in (((("baseline"), "Base"), "gsm8krep3-baseline"),
                                   ((("vestigekv"), "Vk"), "gsm8krep3-vestigekv"))}
    have_rep = {m: r for m, r in rep.items() if r}
    if {"Base", "Vk"} <= set(have_rep):
        for mac, first in (("Base", "BaseI"), ("Vk", "VkI")):
            if first not in got:
                continue
            spread = abs(have_rep[mac][0] - got[first][0])
            lines.append(f"\\newcommand{{\\gsmRepeat{mac}}}{{{spread}}}")
            print(f"  repeat {mac:5} {have_rep[mac][0]} vs {got[first][0]}"
                  f"   spread {spread} questions")
    else:
        for mac in ("Base", "Vk"):
            lines.append(f"\\newcommand{{\\gsmRepeat{mac}}}{{\\PENDING}}")
        print("  PENDING: gsm8krep3-{baseline,vestigekv} not run yet; the "
              "reproducibility spread is unmeasured")

    if a.emit:
        open(OUT, "w").write("\n".join(lines) + "\n")
        print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
