#!/usr/bin/env python3
"""Figure 2's right panel: decode throughput against batch, at two contexts.

    python mexp/kimi/make_throughput_numbers.py            # report
    python mexp/kimi/make_throughput_numbers.py --emit     # write the macros
    python mexp/kimi/make_throughput_numbers.py --check    # exit 1 on a mismatch

THE METRIC, AND THE TWO THINGS IT REPLACED. A point is the mean of the
server's own `gen throughput (token/s)` over a window in which `#running-req`
is constant and equal to the batch the point claims. That column is the
batch's decoded tokens per second, so it excludes prefill by construction and
assumes nothing about how many requests were resident.

It replaces `output_throughput` from the client, which divides decoded tokens
by the whole benchmark -- a third of which is prefill at bs=1, and prefill is
where VestigeKV is slower, so the dilution ran against us.

It also replaces `bs / mean_itl`, which excluded prefill correctly and was
still wrong: an average ITL says nothing about how many requests produced it.
The server log says the batch frequently was not the batch requested --

    64k   bs=1..24  #running-req exactly bs on every decode line   valid
    64k   bs=32     31 for 102 lines, then one request alone       invalid
    128k  bs=4      2 for all 102 lines, 8080 decoded of 16382     invalid
    128k  bs=8      5 for all 102 lines                            invalid

-- because 131072 tokens of prefill per request take long enough that early
requests finish their 4096 decoded tokens before late ones finish prefilling.
At 64k the scheduler completed every prefill before decoding began, the batch
was exact, and the defect was invisible.

So the plateau is not a convenience: it is the only part of a run where the
number on the x-axis is true. A point with no plateau is refused rather than
averaged, because an average over a collapsing batch looks entirely reasonable
and means nothing.
"""
from __future__ import annotations

import argparse
import os
import re
import statistics

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESULTS = os.path.join(ROOT, "results", "kimi")
PAPER = os.path.expanduser("~/vestigekv_paper")
OUT = os.path.join(PAPER, "serving_numbers.tex")

BATCHES = [1, 2, 4, 8, 12, 16, 24, 32]
WORD = {1: "One", 2: "Two", 4: "Four", 8: "Eight", 12: "Twelve", 16: "Sixteen",
        24: "TwentyFour", 32: "ThirtyTwo"}
CONTEXTS = {65536: ("SixtyFour", "tput32"), 131072: ("OneTwentyEight", "tput128k")}
ARMS = {"baseline": "dense", "vestigekv": "vestigekv"}
# 40 decode-log lines is 1600 forward steps: long enough that a rate is a rate
# and not a moment, short enough that a genuine plateau is not thrown away.
MIN_PLATEAU = 40

DECODE = re.compile(r"#running-req:\s*(\d+).*?gen throughput \(token/s\):\s*([\d.]+)")


def plateau(path, bs):
    """(tokens/s, lines) over the longest run with exactly `bs` requests live."""
    rows = []
    for line in open(path, errors="ignore"):
        if "Decode batch" not in line:
            continue
        m = DECODE.search(line)
        if m:
            rows.append((int(m.group(1)), float(m.group(2))))
    best, cur = [], []
    for live, tput in rows:
        if live == bs and tput > 0:
            cur.append(tput)
        else:
            best, cur = (cur if len(cur) > len(best) else best), []
    best = cur if len(cur) > len(best) else best
    if len(best) < MIN_PLATEAU:
        seen = sorted({live for live, _ in rows})
        return None, f"no run of {MIN_PLATEAU}+ decode lines at {bs} live (saw {seen})"
    # drop the plateau's first line: its interval starts before the batch
    # reached this width, so it prices part of another regime
    return statistics.fmean(best[1:]), len(best) - 1


def survey(reps=(None, 2, 3)):
    have, refused = {}, []
    for ctx, (_, prefix) in CONTEXTS.items():
        have[ctx] = {}
        for bs in BATCHES:
            point = {}
            for arm, tag in ARMS.items():
                runs = []
                for rep in reps:
                    job = f"{prefix}-bs{bs}{'' if not rep else 'r%d' % rep}-{tag}"
                    p = os.path.join(RESULTS, f"server_{arm}_{job}.log")
                    if not os.path.exists(p):
                        continue
                    val, why = plateau(p, bs)
                    if val is None:
                        refused.append(f"{job}: {why}")
                    else:
                        runs.append(val)
                if runs:
                    point[arm] = runs
            if len(point) == 2:
                have[ctx][bs] = point
    return have, refused


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    have, refused = survey()
    lines = ["% Generated by mexp/kimi/make_throughput_numbers.py.",
             "% Decoded tokens per second from the server's own decode log, over a",
             "% window where #running-req is constant and equal to the batch; prefill",
             "% is outside it by construction. Ratios are vestigekv/dense."]
    for ctx in sorted(have):
        word = CONTEXTS[ctx][0]
        if not have[ctx]:
            continue
        print(f"  {ctx // 1024}k prefill:")
        for bs in sorted(have[ctx]):
            d = statistics.fmean(have[ctx][bs]["baseline"])
            v = statistics.fmean(have[ctx][bs]["vestigekv"])
            n = min(len(have[ctx][bs]["baseline"]), len(have[ctx][bs]["vestigekv"]))
            print(f"    bs={bs:<3} dense {d:>8.1f}  vk {v:>8.1f}  {v / d:.3f}x  (n={n})")
            lines.append(f"\\newcommand{{\\srvBatch{word}{WORD[bs]}}}{{{v / d:.2f}}}"
                         f"  % {ctx // 1024}k, bs={bs}, n={n}: {v:.1f}/{d:.1f} tok/s")
        if 12 in have[ctx]:
            g = (statistics.fmean(have[ctx][12]["vestigekv"])
                 / statistics.fmean(have[ctx][12]["baseline"]) - 1)
            lines.append(f"\\newcommand{{\\tputGain{word}Twelve}}{{{g * 100:.1f}\\%}}")
    for r in refused:
        print(f"  REFUSED {r}")

    if not any(have.values()):
        raise SystemExit("ABORT: no point has a usable plateau")
    if a.emit:
        open(OUT, "w").write("\n".join(lines) + "\n")
        print(f"wrote {OUT}")
        nums = os.path.join(PAPER, "numbers.tex")
        text = open(nums).read()
        kept = [l for l in text.splitlines()
                if not re.match(r"\\newcommand\{\\tputGainTwelve\}", l.strip())]
        if len(kept) != len(text.splitlines()):
            open(nums, "w").write("\n".join(kept) + "\n")
            print("removed the hand-maintained \\tputGainTwelve from numbers.tex")
    if a.check:
        cur = open(OUT).read()
        for line in lines:
            m = re.match(r"\\newcommand\{\\(\w+)\}", line)
            if m and line.split("%")[0].strip() not in cur:
                raise SystemExit(f"ABORT: the paper's \\{m.group(1)} does not match "
                                 "the sweep on disk. Re-run with --emit.")
        print("check: the throughput macros match the records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
