#!/usr/bin/env python3
"""ROUGE-L on the LongBench v1 summarization records, both arms.

    ~/.venvs/plot/bin/python mexp/kimi/make_lb1_numbers.py [--emit]

Scoring is LongBench's eval.py verbatim: py-rouge `Rouge().get_scores([pred],
[ref], avg=True)["rouge-l"]["f"]`, 0 on a scorer exception, max over the
reference answers, 100 x mean over the subset rounded to two places. That is
what the published LongBench tables are, so a number here is comparable to
one there. py-rouge lives in the plotting venv, not the serving one.
"""
from __future__ import annotations

import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
RESULTS = os.path.join(ROOT, "results", "kimi", "longbench1")
OUT = os.path.expanduser("~/vestigekv_paper/lb1_numbers.tex")
SUBSETS = ["gov_report", "qmsum", "multi_news"]
ARMS = {"baseline": "Dense", "vestigekv": "Vk"}
WORD = {"gov_report": "GovReport", "qmsum": "QMSum", "multi_news": "MultiNews"}


def rouge_l(prediction, ground_truth):
    from rouge import Rouge

    try:
        return Rouge().get_scores([prediction], [ground_truth], avg=True)["rouge-l"]["f"]
    except Exception:
        return 0.0


def score(path):
    rows = [json.loads(l) for l in open(path) if l.strip()]
    total = 0.0
    for r in rows:
        total += max(rouge_l(r["pred"], g) for g in r["answers"])
    return round(100 * total / len(rows), 2), len(rows), sum(r["truncated"] for r in rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    a = ap.parse_args()
    got = {}
    for arm in ARMS:
        for s in SUBSETS:
            p = os.path.join(RESULTS, f"pred_{arm}_{s}.jsonl")
            if os.path.exists(p):
                got[(arm, s)] = score(p)
    if not got:
        print("PENDING: no longbench1 records")
        return 0
    lines = ["% Generated by mexp/kimi/make_lb1_numbers.py from results/kimi/longbench1/.",
             "% ROUGE-L F1 x 100, LongBench eval.py scoring (py-rouge), greedy, seed 0."]
    print(f"{'subset':12} {'dense':>8} {'vestigekv':>10}   n  truncated")
    for s in SUBSETS:
        cells = []
        for arm, mac in ARMS.items():
            v = got.get((arm, s))
            if v:
                lines.append(f"\\newcommand{{\\lbOne{WORD[s]}{mac}}}{{{v[0]:.2f}}}  % n={v[1]}, {v[2]} truncated")
            cells.append(f"{v[0]:8.2f}" if v else f"{'pending':>8}")
        n = got.get(("baseline", s), got.get(("vestigekv", s)))
        print(f"{s:12} {cells[0]} {cells[1]:>10}   {n[1]}  {n[2]}")
    means = {}
    for arm, mac in ARMS.items():
        vals = [got[(arm, s)][0] for s in SUBSETS if (arm, s) in got]
        if len(vals) == len(SUBSETS):
            means[arm] = sum(vals) / len(vals)
            lines.append(f"\\newcommand{{\\lbOneMean{mac}}}{{{means[arm]:.2f}}}")
    if len(means) == 2:
        print(f"{'mean':12} {means['baseline']:8.2f} {means['vestigekv']:10.2f}")
    if a.emit:
        with open(OUT, "w") as f:
            f.write("\n".join(lines) + "\n")
        print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
