#!/usr/bin/env python3
"""Macros for the observed-attention baselines (H2O, SnapKV, StreamingLLM).

    python mexp/kimi/make_baselines_numbers.py [--out ~/vestigekv_paper/baselines_numbers.tex]

These were hand-maintained values naming baselines_8192.json and
h2orecent_8192.json, records that are in no surviving tree. The runs are
reproducible from their pre-registration, so they were re-run rather than left
unbacked, at seed 0 to match every other harness record the paper prints.

One cell moves against the hand-maintained set: SnapKV at 32x read 0.04 and
reads 0.00 here. That is one trial of 24, which is the resolution of the
protocol, and the earlier value came from a run at a different seed. The
caption says so rather than presenting 0.00 as a finding.

A trial is intact when the answer-token NLL stays within 1 nat of dense, the
same bar as every other needle number in this paper.
"""
from __future__ import annotations

import argparse
import collections
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RECORDS = {"": ("results/harness_baselines_8192.json", 8192),
           "L": ("results/harness_baselines_32768.json", 32768)}
# op -> macro infix, ratio -> macro suffix. The paper prints three ratios.
OPS = {"h2o": "HtwoOx", "snapkv": "SnapKVx", "h2o_recent": "HRecx"}
RATIO = {8: "Eight", 32: "ThirtyTwo", 128: "OTE"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/baselines_numbers.tex"))
    a = ap.parse_args()

    L = ["% Generated by mexp/kimi/make_baselines_numbers.py from results/. "
         "Do not edit by hand."]
    for fam, (rel, _) in RECORDS.items():
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p):
            raise SystemExit(f"ABORT: {rel} is not on disk")
        d = json.load(open(p))
        agg = collections.defaultdict(list)
        for r in d["rows"]:
            if r.get("kind") == "needle":
                agg[(r["op"], round(1 / r["rho"]))].append(r["d"])
        L.append(f"% {rel}: seed {d['args']['seed']}, {d['needle_trials']} "
                 f"trials, L={d['L']}. One trial is {1 / d['needle_trials']:.2f}.")
        ns = set()
        for op, infix in OPS.items():
            if fam == "L" and op == "h2o_recent":
                continue            # the recency-protected arm was run at 8k only
            for ratio, suffix in RATIO.items():
                v = agg.get((op, ratio))
                name = f"bl{infix.replace('x', fam + 'x' + fam)}{suffix}" if fam else f"bl{infix}{suffix}"
                if not v:
                    L.append(f"\\newcommand{{\\{name}}}{{\\PENDING}}")
                    continue
                ns.add(len(v))
                L.append(f"\\newcommand{{\\{name}}}"
                         f"{{{sum(x < 1 for x in v) / len(v):.2f}}}")
        if len(ns) == 1 and not fam:
            L.append(f"\\newcommand{{\\blTrials}}{{{ns.pop()}}}")
            L.append(f"\\newcommand{{\\blOneTrial}}{{{1 / d['needle_trials']:.2f}}}")

    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out}: {sum(1 for x in L if x.startswith(chr(92)))} macros")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
