"""Regenerate the RULER macros of the paper (vestigekv_paper/ruler_numbers.tex)
from the run records under results/.

    python mexp/kimi/make_ruler_numbers.py [--out ~/vestigekv_paper/ruler_numbers.tex]

Kimi Linear: results/kimi/ruler/results_{baseline,vestigekv}_n10_4096-...-65536.json
(and the 128k-1M files once measured; \\PENDING until then). GLM-5.3-Flash (the
DSA-trained contrast): results/glm53/ruler/results_{baseline,vestigekv}_*.json.
The recall-margin sweep comes from results/kimi/ruler_vestigekv_margin-*.log.
"""

import argparse
import glob
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
TASKS = ["niah_single_1", "niah_single_2", "niah_single_3", "niah_multikey_1", "niah_multikey_2",
         "niah_multikey_3", "niah_multiquery", "niah_multivalue", "ruler_vt", "ruler_cwe", "ruler_fwe",
         "ruler_qa_squad", "ruler_qa_hotpot"]
SHORT = {"niah_single_1": "NiahSa", "niah_single_2": "NiahSb", "niah_single_3": "NiahSc",
         "niah_multikey_1": "NiahMKa", "niah_multikey_2": "NiahMKb", "niah_multikey_3": "NiahMKc",
         "niah_multiquery": "NiahMQ", "niah_multivalue": "NiahMV", "ruler_vt": "VT", "ruler_cwe": "CWE",
         "ruler_fwe": "FWE", "ruler_qa_squad": "QAsq", "ruler_qa_hotpot": "QAhp"}
LEN = {4096: "FourK", 8192: "EightK", 16384: "SixteenK", 32768: "ThirtyTwoK", 65536: "SixtyFourK",
       131072: "OneTwoEightK", 262144: "TwoFiveSixK", 524288: "FiveTwelveK", 1048576: "OneM"}


def load(line, arm, n, lengths):
    p = os.path.join(ROOT, "results", line, "ruler", f"results_{arm}_n{n}_{'-'.join(map(str, lengths))}.json")
    return json.load(open(p)) if os.path.exists(p) else None


def cell(r, t, l):
    row = r["results"].get(t, {})
    v = row.get(f"{l},none", row.get(str(l)))
    return None if v is None else float(v)


def fmt(v):
    return "\\PENDING" if v is None else f"{v:.2f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser("~/vestigekv_paper/ruler_numbers.tex"))
    args = ap.parse_args()
    L = ["% Generated by mexp/kimi/make_ruler_numbers.py from results/. Do not edit by hand."]
    # n is per line, not global: the Kimi grid is measured at 50 per cell (one
    # sample moves a cell by 0.02), the long grid at 5, GLM-5.3 at 10.
    for line, tag, n, lengths in (("kimi", "K", 50, [4096, 8192, 16384, 32768, 65536]),
                                  ("kimi", "KL", 5, [131072, 262144, 524288, 1048576]),
                                  ("glm53", "G", 10, [4096, 8192, 16384, 32768, 65536])):
        arms = {"D": load(line, "baseline", n, lengths), "V": load(line, "vestigekv", n, lengths)}
        for a, r in arms.items():
            for t in TASKS:
                vals = [cell(r, t, l) if r else None for l in lengths]
                for l, v in zip(lengths, vals):
                    L.append(f"\\newcommand{{\\ruler{tag}{a}{SHORT[t]}{LEN[l]}}}{{{fmt(v)}}}")
                m = None if any(v is None for v in vals) else sum(vals) / len(vals)
                L.append(f"\\newcommand{{\\ruler{tag}{a}{SHORT[t]}Mean}}{{{'\\PENDING' if m is None else f'{m:.3f}'}}}")
            for l in lengths:
                vals = [cell(r, t, l) if r else None for t in TASKS]
                m = None if any(v is None for v in vals) else sum(vals) / len(vals)
                L.append(f"\\newcommand{{\\ruler{tag}{a}Mean{LEN[l]}}}{{{'\\PENDING' if m is None else f'{m:.3f}'}}}")
            allv = [cell(r, t, l) if r else None for t in TASKS for l in lengths]
            m = None if any(v is None for v in allv) else sum(allv) / len(allv)
            L.append(f"\\newcommand{{\\ruler{tag}{a}Mean}}{{{'\\PENDING' if m is None else f'{m:.3f}'}}}")
            L.append(f"\\newcommand{{\\ruler{tag}{a}Wall}}{{{'\\PENDING' if r is None else f'{r['wall_s'] / 60:.0f}'}}}")
        if arms["D"] and arms["V"]:
            d = [cell(arms["V"], t, l) - cell(arms["D"], t, l) for t in TASKS for l in lengths]
            L.append(f"\\newcommand{{\\ruler{tag}Delta}}{{{sum(d) / len(d):+.3f}}}")
            # Per-task deltas. The limitation section classifies the thirteen
            # tasks by their generator parameters and shows the loss sitting
            # only where the haystack is itself made of key-value pairs, so
            # each delta has to be a macro rather than a number typed into
            # prose that a re-run would silently invalidate.
            for t in TASKS:
                dv = [cell(arms["V"], t, l) - cell(arms["D"], t, l) for l in lengths]
                L.append(f"\\newcommand{{\\ruler{tag}Delta{SHORT[t]}}}"
                         f"{{{sum(dv) / len(dv):+.3f}}}")
            L.append(f"\\newcommand{{\\ruler{tag}Worse}}{{{sum(x < -1e-9 for x in d)}}}")
            L.append(f"\\newcommand{{\\ruler{tag}Better}}{{{sum(x > 1e-9 for x in d)}}}")
            L.append(f"\\newcommand{{\\ruler{tag}Cells}}{{{len(d)}}}")
    # The serving telemetry these macros come from lives in the server logs,
    # which are not retained in the archive (see results/kimi/vkstats_extract.json).
    # Prefer the log when it is there -- re-running a job regenerates it -- and
    # fall back to the extract so the macros stay reproducible either way.
    _vk_extract = {}
    _xp = os.path.join(ROOT, "results", "kimi", "vkstats_extract.json")
    if os.path.exists(_xp):
        _vk_extract = {k: v for k, v in json.load(open(_xp)).items()
                       if not k.startswith("_")}

    def vkstats(job):
        s = os.path.join(ROOT, "results", "kimi", f"server_vestigekv_{job}.log")
        if os.path.exists(s):
            last = [l for l in open(s, errors="replace") if "VKSTATS" in l and "TP1]" not in l]
            m = re.search(r"steps=(\d+).*?fetch\[p50=(\d+) p90=(\d+) p99=(\d+)\] fallback=([0-9.]+)",
                          last[-1]) if last else None
            if m:
                return {"steps": int(m.group(1)), "fetch_p50": int(m.group(2)),
                        "fetch_p90": int(m.group(3)), "fetch_p99": int(m.group(4)),
                        "fallback": float(m.group(5))}
        return _vk_extract.get(job)

    # recall-margin sweep (per-job client logs; the targeted tasks at 16k/32k/64k)
    for job, mac in (("margin-0", "Zero"), ("margin-1", "One"), ("margin-2", "Two"), ("margin-3", "Three"),
                     ("margin-lse-2.3", "LseA"), ("margin-lse-4.6", "LseB")):
        p = os.path.join(ROOT, "results", "kimi", f"ruler_vestigekv_{job}.log")
        if not os.path.exists(p):
            continue
        txt = open(p, errors="replace").read()
        cells = {}
        for t in ("niah_single_1", "niah_multikey_2", "niah_multikey_3", "ruler_fwe", "ruler_qa_hotpot"):
            m = re.search(rf"^{t} (\{{.*\}})$", txt, flags=re.M)
            if m:
                d = eval(m.group(1))
                cells[t] = [float(v) for v in d.values()]
        if len(cells) == 5:
            allc = [v for vs in cells.values() for v in vs]
            tgt = [v for t in ("niah_multikey_2", "niah_multikey_3", "ruler_qa_hotpot") for v in cells[t]]
            L.append(f"\\newcommand{{\\sweep{mac}Mean}}{{{sum(allc) / len(allc):.3f}}}")
            L.append(f"\\newcommand{{\\sweep{mac}Targeted}}{{{sum(tgt) / len(tgt):.3f}}}")
            L.append(f"\\newcommand{{\\sweep{mac}MKc}}{{{sum(cells['niah_multikey_3']) / 3:.3f}}}")
            L.append(f"\\newcommand{{\\sweep{mac}QAhp}}{{{sum(cells['ruler_qa_hotpot']) / 3:.3f}}}")
        v = vkstats(job)
        if v:
            L.append(f"\\newcommand{{\\sweep{mac}FetchFifty}}{{{v['fetch_p50']}}}")
            L.append(f"\\newcommand{{\\sweep{mac}Fallback}}{{{v['fallback']:.2f}}}")
    # calibrated-regime stats (stream 128k, stats on) and the 64k short-answer regime
    for job, mac in (("stats-vestigekv-stream-128k", "StreamOneTwoEight"), ("stats-vestigekv-ruler-64k", "RulerSixtyFour")):
        v = vkstats(job)
        if v:
            L.append(f"\\newcommand{{\\stats{mac}Steps}}{{{v['steps']}}}")
            L.append(f"\\newcommand{{\\stats{mac}FetchFifty}}{{{v['fetch_p50']}}}")
            L.append(f"\\newcommand{{\\stats{mac}FetchNinety}}{{{v['fetch_p90']}}}")
            L.append(f"\\newcommand{{\\stats{mac}FetchNinetyNine}}{{{v['fetch_p99']}}}")
            L.append(f"\\newcommand{{\\stats{mac}Fallback}}{{{v['fallback']:.3f}}}")
    open(args.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {args.out}: {len(L)} macros")


if __name__ == "__main__":
    main()
