"""Regenerate the LongBench v2 macros of the paper (vestigekv_paper/lb2_numbers.tex)
from results/kimi/longbench2/results_{baseline,vestigekv}.json.

    python mexp/kimi/make_lb2_numbers.py [--out ~/vestigekv_paper/lb2_numbers.tex]

Both arms answer the same 300 questions (the <= 120k-token subset), so the paired
difference is the quantity, not the two accuracies; \\lbDelta carries it signed.
An arm that has not run yet emits \\PENDING rather than a number, which errors at
build time instead of printing a stale one.
"""

import argparse
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
RESULTS = os.path.join(ROOT, "results", "kimi", "longbench2")
ARMS = {"baseline": "D", "vestigekv": "V"}  # dense / vestigekv, as in ruler_numbers
# Which record each arm's row comes from, named rather than globbed. Three
# tagged vestigekv records exist -- the timed arm, the stats arm, and a caldump
# diagnostic -- and only one of them is the table's. The paired counts below
# read the SAMPLES of these same records: pairing today's accuracies against an
# older run's per-question answers produces a gain/loss split that belongs to
# neither run.
RECORD = {"baseline": "baseline_lb2-baseline",
          "vestigekv": "vestigekv_lb2-vestigekv"}
# The official domain names, shortened for a macro name.
DOMAINS = {
    "Single-Document QA": "SingleDoc",
    "Multi-Document QA": "MultiDoc",
    "Long-dialogue History Understanding": "Dialogue",
    "Long In-context Learning": "ICL",
    "Code Repository Understanding": "Code",
    "Long Structured Data Understanding": "Structured",
}
DIFFICULTY = {"easy": "Easy", "hard": "Hard"}
LENGTH = {"short": "Short", "medium": "Medium", "long": "Long"}


def _load(arm):
    """arm is a filename stem: 'baseline', 'vestigekv', or a tagged variant.

    The untagged name is preferred, and a job-tagged one is accepted when no
    untagged record exists: the LongBench client names its own output and
    tags it with the job id, so `lb2-baseline` lands as
    `results_baseline_lb2-baseline.json` and this used to find nothing and
    emit PENDING for a run that had completed. Mirrors the same fallback in
    make_ruler_numbers.load().

    Ambiguity is refused rather than resolved: with two tagged records and no
    untagged one there is no rule here that says which run the table means,
    and picking the alphabetically first is how a paper ends up quoting a
    diagnostic arm.
    """
    path = os.path.join(RESULTS, f"results_{arm}.json")
    if os.path.exists(path):
        return json.load(open(path))
    tagged = sorted(glob.glob(os.path.join(RESULTS, f"results_{arm}_*.json")))
    if len(tagged) > 1:
        raise SystemExit(
            f"ABORT: {len(tagged)} tagged LongBench records for '{arm}' and no "
            "untagged one; name the run the table means:\n  "
            + "\n  ".join(os.path.basename(t) for t in tagged))
    if tagged:
        print(f"   note: {arm} read from {os.path.basename(tagged[0])} (tagged)")
        return json.load(open(tagged[0]))
    return None


def _cells(res, tag):
    """(macro suffix, value) for one arm, or PENDING values when it has not run."""
    out = [("Acc", res["acc"] if res else None), ("N", res["n"] if res else None)]
    for key, table in (("domain", DOMAINS), ("difficulty", DIFFICULTY), ("length", LENGTH)):
        for name, short in table.items():
            cell = res["by"][key].get(name) if res else None
            out.append((short, cell["acc"] if cell else None))
    return [(f"lbK{tag}{suffix}", v) for suffix, v in out]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser("~/vestigekv_paper/lb2_numbers.tex"))
    args = ap.parse_args()

    loaded = {arm: _load(RECORD.get(arm, arm)) for arm in ARMS}
    lines = ["% Generated by mexp/kimi/make_lb2_numbers.py from results/. Do not edit by hand."]
    for arm, tag in ARMS.items():
        for name, v in _cells(loaded[arm], tag):
            if v is None:
                lines.append(f"\\newcommand{{\\{name}}}{{\\PENDING}}")
            elif name.endswith("N"):
                lines.append(f"\\newcommand{{\\{name}}}{{{int(v)}}}")
            else:
                lines.append(f"\\newcommand{{\\{name}}}{{{v:.3f}}}")
    d, v = loaded["baseline"], loaded["vestigekv"]
    # The logprob pair, kept as the exactness check and NOT as a result. Scoring
    # the four choices from the first token reads logits produced by
    # forward_extend, which the compression does not touch, so the two arms are
    # equal by construction; printing both accuracies is what shows it, and an
    # inequality here would mean the premise is wrong. RECORD points at the
    # GENERATE pair instead, whose max_tokens puts real decode steps on the
    # compressed path, and every other macro in this file comes from that pair.
    for arm, tag in (("baseline", "D"), ("vestigekv", "V")):
        lp = _load(arm)
        lines.append(f"\\newcommand{{\\lbKLogprob{tag}}}{{"
                     + (f"{lp['acc']:.3f}" if lp else "\\PENDING") + "}")
    # Wall clock on the same 300 questions, matched arms, at the generate
    # protocol's max_tokens: a 120k prefill plus that many decode steps per
    # question. So this is end-to-end cost on real documents, not a prefill
    # figure -- the earlier comment here said max_tokens=1 and "essentially no
    # decode", which described the logprob pair above and not these records.
    if d and v and d.get("wall_s") and v.get("wall_s"):
        dw, vw = float(d["wall_s"]), float(v["wall_s"])
        lines.append(f"\\newcommand{{\\lbKDWall}}{{{dw / 60:.1f}}}")
        lines.append(f"\\newcommand{{\\lbKVWall}}{{{vw / 60:.1f}}}")
        lines.append(f"\\newcommand{{\\lbKSpeed}}{{{dw / vw:.3f}}}")
        lines.append(f"\\newcommand{{\\lbKCost}}{{{100 * (vw / dw - 1):+.1f}}}")
        # The second vestigekv run bounds run-to-run spread on this harness.
        v2 = _load("vestigekv_lb2-vestigekv-stats")
        if v2 and v2.get("wall_s"):
            lines.append(f"\\newcommand{{\\lbKVSpread}}{{"
                         f"{100 * abs(float(v2['wall_s']) / vw - 1):.2f}}}")
    else:
        lines += [f"\\newcommand{{\\lbK{n}}}{{\\PENDING}}"
                  for n in ("DWall", "VWall", "Speed", "Cost", "VSpread")]
    if d and v:
        delta = v["acc"] - d["acc"]
        lines.append(f"\\newcommand{{\\lbKDelta}}{{{delta:+.3f}}}")
        # Questions the arms answer differently, in each direction: what a paired
        # claim rests on, where two accuracies that match can still hide a swap.
        by_id = {r["_id"]: r for r in json.load(
            open(os.path.join(RESULTS, f"samples_{RECORD['baseline']}.json")))}
        vs = json.load(
            open(os.path.join(RESULTS, f"samples_{RECORD['vestigekv']}.json")))
        gain = sum(1 for r in vs if r["acc"] > by_id[r["_id"]]["acc"])
        loss = sum(1 for r in vs if r["acc"] < by_id[r["_id"]]["acc"])
        lines.append(f"\\newcommand{{\\lbKGain}}{{{gain}}}")
        lines.append(f"\\newcommand{{\\lbKLoss}}{{{loss}}}")
    else:
        lines += [f"\\newcommand{{\\lbK{n}}}{{\\PENDING}}" for n in ("Delta", "Gain", "Loss")]
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(lines) - 1} macros)")


if __name__ == "__main__":
    main()
