#!/usr/bin/env python3
"""Macros for the controlled rotation ablation behind the NoPE dividend.

    python mexp/kimi/make_rotation_numbers.py [--out ~/vestigekv_paper/rotation_numbers.tex]

The paper's one quantitative statement of the dividend used to be a pair of
union figures for Kimi Linear against DeepSeek-V2. Those two models differ in
architecture, width, training data and recipe as well as in position encoding,
so the pair measured the distance between two models and was quoted as the
cost of rotation. It also came from entropy.py, which is in no surviving tree,
so it could not be regenerated. Both macros are retired.

What replaces them is a controlled ablation: one checkpoint, one prefill, the
same cached rows and the same absorbed queries, scored twice, with the
decoupled branch left as the model stores it and then rotated synthetically.
R is the only thing that changes, which is what Proposition "Rank stability"
is about.

Two honest limits, both printed as macros so the body cannot quietly drop them:

  The rows were never shaped by rotation-aware training, so this isolates the
  geometry of R, not what a RoPE-trained cache would look like.

  Eq. (beta) is a supremum over an equidistributed phase. At a few thousand
  tokens the lowest RoPE frequencies have barely turned, so the torus closed
  form is an upper limit the context has not reached; res_rope_torus is
  emitted next to the measured res_rope_emp rather than in place of it.

The union effect depends strongly on k, so both are emitted. A wider kept set
is harder for any single pair's beta to disturb, which is the proposition's
own prediction, so reporting only the larger (k=1) ratio would be quoting the
most favourable corner of a known trend.
"""
from __future__ import annotations

import argparse
import json
import os
import statistics

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# k -> record. The k=1 record carries the headline ratio, the k=64 record the
# residual spectrum as well (both records compute it; they must agree).
RECORDS = {1: "results/harness_rotation_k1_8192.json",
           64: "results/harness_rotation_8192.json"}
HEAD_K = 64          # the k whose union the table prints as an absolute share


def rng(v, pct=True, prec=1):
    lo, hi = min(v), max(v)
    if pct:
        return (f"{100 * lo:.{prec}f}\\%" if abs(hi - lo) < 5e-4
                else f"{100 * lo:.{prec}f}--{100 * hi:.{prec}f}\\%")
    return (f"{lo:.{prec}f}$\\times$" if abs(hi - lo) < 5e-3
            else f"{lo:.{prec}f}--{hi:.{prec}f}$\\times$")


def load(rel):
    p = os.path.join(ROOT, rel)
    if not os.path.exists(p):
        raise SystemExit(f"ABORT: {rel} is not on disk")
    d = json.load(open(p))
    if not d.get("union"):
        raise SystemExit(f"ABORT: {rel} carries no union rows")
    n = {r["layer"]: r for r in d["union"] if r["pe"] == "nope"}
    o = {r["layer"]: r for r in d["union"] if r["pe"] == "rope"}
    if set(n) != set(o):
        raise SystemExit(f"ABORT: {rel} scored the two conditions on "
                         f"different layers")
    return d, n, o


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/rotation_numbers.tex"))
    a = ap.parse_args()

    L = ["% Generated by mexp/kimi/make_rotation_numbers.py from results/. "
         "Do not edit by hand."]
    ctx = steps = layers = None
    for k, rel in sorted(RECORDS.items()):
        d, n, o = load(rel)
        # The control: the two conditions must differ ONLY in rotation, so
        # every scalar describing the run has to match across them.
        for lay in n:
            for f in ("T", "K", "steps"):
                if n[lay][f] != o[lay][f]:
                    raise SystemExit(
                        f"ABORT: layer {lay} of {rel} disagrees on {f} "
                        f"between the two conditions, so rotation is not the "
                        f"only variable")
        if {r["K"] for r in d["union"]} != {k}:
            raise SystemExit(f"ABORT: {rel} is not a k={k} record")
        ratios = [o[l]["union_frac"] / n[l]["union_frac"] for l in n]
        if not all(r > 1 for r in ratios):
            print(f"NOTE: {sum(r <= 1 for r in ratios)} of {len(ratios)} "
                  f"layers do not inflate at k={k}; the body claims one "
                  f"direction in every layer, so check it before printing.")
        sfx = "Top" if k == 1 else ""
        L.append(f"% {rel}: k={k}, {len(n)} MLA layers, "
                 f"median inflation {statistics.median(ratios):.2f}x")
        L.append(f"\\newcommand{{\\rotUnionNope{sfx}}}"
                 f"{{{rng([n[l]['union_frac'] for l in n], prec=2)}}}")
        L.append(f"\\newcommand{{\\rotUnionRope{sfx}}}"
                 f"{{{rng([o[l]['union_frac'] for l in n], prec=2)}}}")
        L.append(f"\\newcommand{{\\rotUnionRatio{sfx}}}"
                 f"{{{rng(ratios, pct=False)}}}")
        ctx, steps, layers = d["T"], n[min(n)]["steps"], len(n)
        if k == HEAD_K:
            L.append(f"\\newcommand{{\\rotUnionK}}{{{k}}}")
            sp = d.get("spectrum", [])
            if not sp:
                raise SystemExit(f"ABORT: {rel} carries no spectrum rows")
            L.append(f"% {rel}: rank-{sp[0]['r']} residual energy fraction "
                     f"over {sp[0]['d']} dims, {sp[0]['d_rot']} of them rotated")
            L.append(f"\\newcommand{{\\rotR}}{{{sp[0]['r']}}}")
            L.append(f"\\newcommand{{\\rotResNope}}"
                     f"{{{rng([r['res_nope'] for r in sp], prec=1)}}}")
            L.append(f"\\newcommand{{\\rotResRope}}"
                     f"{{{rng([r['res_rope_emp'] for r in sp], prec=1)}}}")
            L.append(f"\\newcommand{{\\rotResTorus}}"
                     f"{{{rng([r['res_rope_torus'] for r in sp], prec=1)}}}")
            L.append(f"\\newcommand{{\\rotResRatio}}"
                     f"{{{rng([r['res_rope_emp'] / r['res_nope'] for r in sp], pct=False)}}}")

    L.append(f"\\newcommand{{\\rotSteps}}{{{steps}}}")
    L.append(f"\\newcommand{{\\rotLayers}}{{{layers}}}")
    L.append(f"\\newcommand{{\\rotCtx}}{{{ctx}}}")
    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out}: {sum(1 for x in L if x.startswith(chr(92)))} macros")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
