#!/usr/bin/env python3
"""Write the README's quality tables from the records the paper's macros read.

    python mexp/kimi/make_readme_tables.py           # print, compare
    python mexp/kimi/make_readme_tables.py --emit    # rewrite the README block

The block between the two `<!-- quality-tables:... -->` markers in README.md is
generated; nothing inside it is typed. Every number comes through the same
parsers the paper's macro generators use (make_ruler_numbers, make_gsm8k_numbers)
or from the MAUVE verdict records under results/quality/, so the README, the
paper and the records cannot disagree without this script saying so.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

import make_gsm8k_numbers as gsm  # noqa: E402
import make_ruler_numbers as ruler  # noqa: E402

README = os.path.join(ROOT, "README.md")
BEGIN = "<!-- quality-tables:begin (generated by mexp/kimi/make_readme_tables.py; do not edit) -->"
END = "<!-- quality-tables:end -->"
QUALITY = os.path.join(ROOT, "results", "quality")
LENGTHS = [4096, 8192, 16384, 32768, 65536]
N_RULER = 50
# (display, ruler line, gsm8k macro suffix, mauve record suffix)
CHECKPOINTS = [("Base", "kimi_base", "", "base"), ("Instruct", "kimi", "I", "instruct")]
SETUP = "Kimi-Linear-48B-A3B, 2x RTX PRO 6000 Blackwell, TP=2"


def mauve(name):
    p = os.path.join(QUALITY, name)
    if not os.path.exists(p):
        return None
    j = json.load(open(p))
    return j["mauve_eng"], j["mauve_vk"], j["n_ctx"], j["gen_tokens"], j["verdict"]


def fmt_pct(v):
    return "pending" if v is None else f"{v:.2f}"


def headline_rows():
    """The four (checkpoint x arm) cells the paper's Table 1 prints."""
    rows = []
    # GSM8K-Platinum: counts, the way the macros carry them
    cells = []
    for _, _, suf, _ in CHECKPOINTS:
        for arm, mac in (("baseline", "Base"), ("vestigekv", "Vk")):
            r = gsm.read(arm, gsm.ARMS[(arm, mac + suf)])
            cells.append("pending" if r is None else f"{r[0]} / {r[1]} ({100 * r[0] / r[1]:.1f}%)")
    rows.append(("GSM8K-Platinum, 64-shot, full set", cells))
    # MAUVE, short and long prefill
    for label, stem in (("MAUVE, 4k prefill", "quality_mauve_scores_{}.json"),
                        ("MAUVE, 64k prefill", "quality_mauve64k64_verdict{}.json")):
        cells, note = [], ""
        for _, _, _, msuf in CHECKPOINTS:
            name = stem.format(msuf if "scores" in stem else ("_" + msuf if msuf == "instruct" else ""))
            m = mauve(name)
            if m is None:
                cells += ["pending", "pending"]
                continue
            eng, vk, n_ctx, gen, verdict = m
            cells += [f"{eng:.4f}", f"{vk:.4f}"]
            note = f" ({n_ctx} contexts x {gen} generated tokens, gate vk >= dense - 0.10: {verdict})"
        rows.append((label + note, cells))
    # RULER mean over the 13-task x 5-length grid
    cells = []
    for _, line, _, _ in CHECKPOINTS:
        for arm in ("baseline", "vestigekv"):
            r = ruler.load(line, arm, N_RULER, LENGTHS)
            vals = [ruler.cell(r, t, l) for t in ruler.TASKS for l in LENGTHS] if r else []
            vals = [v for v in vals if v is not None]
            cells.append("pending" if not vals else f"{sum(vals) / len(vals):.3f}")
    rows.append((f"RULER mean, 13 tasks x 4k-64k, n={N_RULER}/cell", cells))
    # LongBench v1 summarisation, ROUGE-L: the lb1sum pair ran on the Instruct
    # checkpoint only (mexp/kimi/queue.jsonl, lb1sum-*); the Base cells are
    # not pending, they are not planned.
    import make_lb1_numbers as lb1  # noqa: E402
    lb = os.path.join(ROOT, "results", "kimi", "longbench1")
    cells = ["--", "--"]
    for arm in ("baseline", "vestigekv"):
        vals = []
        for sub in lb1.SUBSETS:
            f = os.path.join(lb, f"pred_{arm}_{sub}.jsonl")
            if os.path.exists(f):
                vals.append(lb1.score(f)[0])
        cells.append(f"{sum(vals) / len(vals):.2f}" if len(vals) == len(lb1.SUBSETS) else "pending")
    rows.append(("LongBench v1 summarisation, ROUGE-L F1 x 100, mean of gov_report/qmsum/multi_news (n=200 each)", cells))
    return rows


def ruler_grid(display, line):
    arms = {a: ruler.load(line, a, N_RULER, LENGTHS) for a in ("baseline", "vestigekv")}
    if any(r is None for r in arms.values()):
        return [f"*RULER grid for {display}: pending*", ""]
    out = [f"**RULER, {display} checkpoint** (dense / VestigeKV, accuracy, n={N_RULER} per cell):", "",
           "| task | " + " | ".join(f"{l // 1024}k" for l in LENGTHS) + " | mean |",
           "|---|" + "---|" * (len(LENGTHS) + 1)]
    col_d = {l: [] for l in LENGTHS}
    col_v = {l: [] for l in LENGTHS}
    for t in ruler.TASKS:
        ds = [ruler.cell(arms["baseline"], t, l) for l in LENGTHS]
        vs = [ruler.cell(arms["vestigekv"], t, l) for l in LENGTHS]
        for l, d, v in zip(LENGTHS, ds, vs):
            if d is not None and v is not None:
                col_d[l].append(d)
                col_v[l].append(v)
        md = [d for d in ds if d is not None]
        mv = [v for v in vs if v is not None]
        cells = [f"{fmt_pct(d)} / {fmt_pct(v)}" for d, v in zip(ds, vs)]
        mean = (f"{sum(md) / len(md):.3f} / {sum(mv) / len(mv):.3f}" if md and mv else "pending")
        out.append(f"| {t} | " + " | ".join(cells) + f" | {mean} |")
    means = [f"{sum(col_d[l]) / len(col_d[l]):.3f} / {sum(col_v[l]) / len(col_v[l]):.3f}"
             if col_d[l] else "pending" for l in LENGTHS]
    alld = [x for l in LENGTHS for x in col_d[l]]
    allv = [x for l in LENGTHS for x in col_v[l]]
    out.append("| **mean** | " + " | ".join(means)
               + f" | **{sum(alld) / len(alld):.3f} / {sum(allv) / len(allv):.3f}** |")
    out.append("")
    return out


def render():
    L = [BEGIN, "", f"**Quality** ({SETUP}; dense = the same tree with `--attention-backend triton`,",
         "VestigeKV = `--attention-backend vestigekv_mla`, seed 0, greedy):", "",
         "| | Base, dense | Base, VestigeKV | Instruct, dense | Instruct, VestigeKV |",
         "|---|---|---|---|---|"]
    for label, cells in headline_rows():
        L.append(f"| {label} | " + " | ".join(cells) + " |")
    L.append("")
    L.append("GSM8K-Platinum is madrylab/gsm8k-platinum (n=1209, label-corrected gsm8k test set), "
             "64-shot, exact match on the final answer. MAUVE is scored against the reference "
             "continuations of the same prompts (`mexp/m7_mauve_serving.py`); the 4k and 64k rows "
             "differ in prefill length. RULER is lm-eval's 13-task suite; the 4k-64k grid below "
             "is the one the paper's Table reads (`mexp/kimi/make_ruler_numbers.py`). Records: "
             "`results/kimi/gsm8k_*`, `results/quality/quality_mauve*.json`, "
             "`results/kimi/ruler/results_*_n50_*.json`. ROUGE-L is LongBench's own scoring "
             "(`mexp/kimi/make_lb1_numbers.py`, records `results/kimi/longbench1/pred_*`), "
             "Instruct checkpoint only.")
    L.append("")
    for display, line, _, _ in CHECKPOINTS:
        L += ruler_grid(display, line)
    L.append(END)
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    a = ap.parse_args()
    block = render()
    text = open(README).read()
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit("ABORT: README.md carries no quality-tables markers")
    new = text[:i] + block + text[j + len(END):]
    if new == text:
        print("README block already current")
        return 0
    if a.emit:
        open(README, "w").write(new)
        print(f"README block rewritten ({block.count(chr(10))} lines)")
    else:
        print(block)
        print("\n(dry run; --emit to write)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
