#!/usr/bin/env python3
"""Figure 2's right panel, reduced from the tput32 sweep.

    python mexp/kimi/make_throughput_numbers.py --emit
    python mexp/kimi/make_throughput_numbers.py --check   # exit 1 on a mismatch

WHY THIS EXISTS AS A CHECK AND NOT ONLY A GENERATOR. The caption already
states the sweep's configuration -- radix cache off on both arms, every point
served by a graph captured at bs=32 -- while serving_numbers.tex still holds
the previous sweep's values, taken with the radix cache on and at a capture
width no surviving record names. A caption describing one run above numbers
from another is the exact failure that cost this paper its RoPE table, and it
is invisible to every other check we have: the macros are defined, the paper
compiles, the figure renders.

So this refuses. Until the tput32 records exist, --check fails and says the
caption is ahead of its data; once they exist, --emit replaces the macros and
--check holds them to the records from then on. Run --check before submitting.
"""
from __future__ import annotations

import argparse
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESULTS = os.path.join(ROOT, "results", "kimi")
PAPER = os.path.expanduser("~/vestigekv_paper")
OUT = os.path.join(PAPER, "serving_numbers.tex")

BATCHES = [1, 4, 12, 24, 32]
WORD = {1: "One", 4: "Four", 12: "Twelve", 24: "TwentyFour", 32: "ThirtyTwo"}


def record(bs, arm):
    """The client JSONL the runner writes for tput32-bs<N>-<arm>."""
    shape = f"64k-4096" + (f"-x{bs}" if bs > 1 else "") + (f"-c{bs}" if bs > 1 else "")
    return os.path.join(RESULTS, f"latency_stream_{shape}_{arm}.jsonl")


def throughput(path):
    with open(path) as f:
        blob = json.loads(f.read())
    for key in ("output_throughput", "output_throughput_tok_s"):
        if key in blob:
            return float(blob[key])
    raise SystemExit(f"ABORT: {path} has no output_throughput field")


def survey():
    have, missing = {}, []
    for bs in BATCHES:
        pair = {}
        for arm in ("baseline", "vestigekv"):
            p = record(bs, arm)
            if os.path.exists(p):
                pair[arm] = throughput(p)
            else:
                missing.append(os.path.relpath(p, ROOT))
        if len(pair) == 2:
            have[bs] = pair
    return have, missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    have, missing = survey()
    for bs in sorted(have):
        d, v = have[bs]["baseline"], have[bs]["vestigekv"]
        print(f"  bs={bs:<3} dense {d:>8.1f}  vk {v:>8.1f}  {v / d:.3f}x")

    if missing:
        msg = ("the caption says the sweep is radix-off with graphs captured at "
               "bs=32, and these records do not exist yet:\n  "
               + "\n  ".join(missing)
               + "\nRun the registered tput32 jobs (README.md) before submitting.")
        if a.check or a.emit:
            raise SystemExit("ABORT: " + msg)
        print("PENDING: " + msg)
        return 0

    lines = ["% Generated by mexp/kimi/make_throughput_numbers.py from the tput32",
             "% sweep: 64k prefill + 4096 decoded tokens, radix cache off on both",
             "% arms, GRAPH_BS=32=MAX_REQS at every point.",
             "% Ratios are vestigekv/dense output_throughput."]
    for bs in sorted(have):
        d, v = have[bs]["baseline"], have[bs]["vestigekv"]
        lines.append(f"\\newcommand{{\\srvBatch{WORD[bs]}}}{{{v / d:.2f}}}"
                     f"  % bs={bs}: {v:.1f}/{d:.1f} tok/s")
    gain = have[12]["vestigekv"] / have[12]["baseline"] - 1
    lines.append(f"\\newcommand{{\\tputGainTwelve}}{{{gain * 100:.1f}\\%}}")
    lines.append("\\newcommand{\\srvBatchList}{"
                 + ", ".join(f"${have[b]['vestigekv'] / have[b]['baseline']:.2f}\\times$"
                             for b in sorted(have)) + "}")

    if a.check:
        cur = open(OUT).read()
        for line in lines:
            name = re.match(r"\\newcommand\{\\(\w+)\}", line)
            if name and line.split("%")[0].strip() not in cur:
                raise SystemExit(
                    f"ABORT: the paper's \\{name.group(1)} does not match the "
                    "sweep on disk. Re-run with --emit.")
        print("check: the throughput macros match the records")
    if a.emit:
        open(OUT, "w").write("\n".join(lines) + "\n")
        print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
