#!/usr/bin/env python3
"""Macros for the trigger telemetry and the teacher-forced CE cost.

    python mexp/kimi/make_trigger_numbers.py [--out ~/vestigekv_paper/trigger_numbers.tex]

Three values the paper prints in its body had neither a record nor the script
that produced one: trigSoundRate and trigConfRec named cert_trigger.log and
gauss_trigger.log, dceVkMed named m6_bpb.json, and none of the three files nor
their generators are in any surviving tree.

All three are quantities the cascade already computes, so they were
instrumented rather than re-derived by hand.

  trigSoundRate: the share of (query, head) for which SOME archived row beats
  the kept tier's per-head maximum under the SOUND Cauchy-Schwarz bound. z is
  measured in units of the Eq. 7 scale, which already carries the divisor
  sqrt(d_c - r), so the sound test is z = sqrt(d_c - r), about 21.2, and not
  z = 1. At z = 1 the same instrument reports 0.04 instead of 0.996, which is
  the difference between "the sound test is usable" and the paper's reading of
  it; the constant matters more than the measurement.

  trigConfRec: the recall the CALIBRATED z reaches on the same calibration
  queries, against a target of 0.90.

  dceVkMed: median teacher-forced Delta CE of the deployed configuration over
  held-out documents. This comes from the prereg21 command (6 documents at
  L=8192, both tiers, rho = 1/32) and is NOT a reproduction of the retired
  m6_bpb.json, whose protocol is not recoverable. It is larger than the value
  that file was quoted for, and is reported as what this protocol measures.
"""
from __future__ import annotations

import argparse
import json
import os
import statistics

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TIER1 = "results/harness_tier1_8192.json"     # trigger telemetry, five selectors
BPB = "results/harness_bpb_8192.json"         # teacher-forced CE
DEPLOYED_RHO = 32                              # the shipped rho denominator


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/trigger_numbers.tex"))
    a = ap.parse_args()

    L = ["% Generated by mexp/kimi/make_trigger_numbers.py from results/. "
         "Do not edit by hand."]

    p = os.path.join(ROOT, TIER1)
    if not os.path.exists(p):
        raise SystemExit(f"ABORT: {TIER1} is not on disk")
    d = json.load(open(p))
    # The deployed selector only: the others are the ablation, and a rate
    # pooled over them would describe no configuration this paper runs.
    t = [x for x in d.get("trigger", [])
         if x.get("op") == "twotier" and round(1 / x["rho"]) == DEPLOYED_RHO]
    if not t:
        raise SystemExit("ABORT: no trigger rows for the deployed selector")
    sr = [x["sound_rate"] for x in t if x.get("sound_rate") is not None]
    cr = [x["conf_rec"] for x in t if x.get("conf_rec") is not None]
    L.append(f"% {TIER1}: deployed selector, rho=1/{DEPLOYED_RHO}, "
             f"{len(t)} (layer, request) scans")
    L.append(f"\\newcommand{{\\trigSoundRate}}{{{100 * statistics.median(sr):.1f}\\%}}")
    L.append(f"\\newcommand{{\\trigConfRec}}{{{statistics.median(cr):.3f}}}")

    p = os.path.join(ROOT, BPB)
    if not os.path.exists(p):
        raise SystemExit(f"ABORT: {BPB} is not on disk")
    b = json.load(open(p))
    ce = [r["d"] for r in b["rows"]
          if r.get("kind") == "ce" and r.get("op") == "twotier"
          and round(1 / r["rho"]) == DEPLOYED_RHO and r.get("d") is not None]
    if not ce:
        raise SystemExit("ABORT: no CE rows for the deployed configuration")
    L.append(f"% {BPB}: {len(ce)} documents, L={b['L']}, rho=1/{DEPLOYED_RHO}")
    L.append(f"\\newcommand{{\\dceVkMed}}{{{statistics.median(ce):+.4f}}}")
    L.append(f"\\newcommand{{\\dceVkDocs}}{{{len(ce)}}}")

    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out}")
    print(f"   trigSoundRate = {100 * statistics.median(sr):.1f}%  "
          f"trigConfRec = {statistics.median(cr):.3f}  "
          f"dceVkMed = {statistics.median(ce):+.4f} over {len(ce)} docs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
