#!/usr/bin/env python3
"""Macros for the 128k serving needle, counted from the run logs.

    python mexp/kimi/make_needle_numbers.py [--out ~/vestigekv_paper/needle_numbers.tex]

\\needleSrv is quoted in the abstract, and it was a hand-maintained value whose
comment named results/quality_needle32_verdict[_instruct].json. Those four
verdict files are in no surviving tree, so the paper's most-read retrieval
number had no record behind it and no script that could rebuild one. The logs
the verdicts were written from DID survive, under runs/2026-09-13/, and they
carry the per-trial outcome rather than a summary, so the count is recoverable
exactly.

The bar is the client's own: needle_serving.py scores `str(code) in text`, an
exact substring of the five-digit code in the generation, and prints one line
per trial with that verdict. This reads those lines and counts them. A log
whose trials do not all agree with the printed total is refused rather than
rounded, because a partial log is what a crashed run leaves behind.
"""
from __future__ import annotations

import argparse
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TRIAL = re.compile(r"^trial (\d+): depth=[\d.]+ intact=(True|False)", re.M)

# One entry per macro: the logs that have to agree, both arms and both
# checkpoints. The needle claim is that NO arm loses a needle, so a single
# count over the union is the honest object: a per-arm count would let one
# arm's miss hide behind another arm's pass.
FAMILIES = {
    "needleSrv": sorted(glob.glob(os.path.join(ROOT, "runs", "2026-09-13", "needle32_*.log"))),
}


def count(path):
    hits = TRIAL.findall(open(path, errors="replace").read())
    if not hits:
        return None
    return sum(v == "True" for _, v in hits), len(hits)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/needle_numbers.tex"))
    a = ap.parse_args()

    lines = ["% Generated by mexp/kimi/make_needle_numbers.py from runs/. "
             "Do not edit by hand."]
    for macro, paths in FAMILIES.items():
        if not paths:
            lines.append(f"\\newcommand{{\\{macro}}}{{\\PENDING}}")
            print(f"  {macro}: no logs found")
            continue
        per = {}
        for p in paths:
            c = count(p)
            if c is None:
                raise SystemExit(f"ABORT: {os.path.basename(p)} has no trial lines")
            per[os.path.basename(p)] = c
        ns = {n for _, n in per.values()}
        if len(ns) != 1:
            raise SystemExit(
                "ABORT: the arms ran different trial counts, so one number "
                "cannot stand for them: "
                + ", ".join(f"{k} {v[1]}" for k, v in per.items()))
        n = ns.pop()
        # Every arm must hit every trial for the claim to read as it does.
        worst = min(k for k, _ in per.values())
        lines.append(f"\\newcommand{{\\{macro}}}{{{worst}/{n}}}")
        for k, v in sorted(per.items()):
            lines.append(f"%   {k}: {v[0]}/{v[1]}")
        print(f"  {macro} = {worst}/{n} over {len(per)} logs")

    with open(a.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
