#!/usr/bin/env python3
"""The model's own shape, for the sentences that bound what a ratio can show.

    python mexp/kimi/make_model_numbers.py --emit

Kimi Linear is a hybrid: most of its layers are linear attention with no KV
cache, and only a minority are full-attention MLA. VestigeKV touches the MLA
layers and nothing else, so every end-to-end ratio in the paper is diluted by
the majority of the step that the method does not reach. A reader who does not
know the split reads a 1.1x end-to-end figure as the method's ceiling; a reader
who does knows it is a floor.

That makes the split load-bearing prose rather than trivia, and load-bearing
prose is not typed. The counts come from the checkpoint's own config, so they
cannot drift from the weights the runs actually served -- and if the paper is
ever rebuilt against a different hybrid, the sentence moves with it instead of
lying.

Both checkpoints are checked: Instruct and Base must agree, or the table's
rows are not describing one architecture and the caption cannot say "the
model" at all.
"""
from __future__ import annotations

import argparse
import glob
import json
import os

OUT = os.path.expanduser("~/vestigekv_paper/model_numbers.tex")
PATTERN = os.path.expanduser(
    "~/.cache/huggingface/hub/models--moonshotai--Kimi-Linear-48B-A3B-*"
    "/snapshots/*/config.json")


def shape(path):
    cfg = json.load(open(path))
    text = cfg.get("text_config", cfg)
    total = text["num_hidden_layers"]
    full = len(text["linear_attn_config"]["full_attn_layers"])
    kda = len(text["linear_attn_config"]["kda_layers"])
    if full + kda != total:
        raise SystemExit(
            f"ABORT: {path} lists {full} full-attention and {kda} linear layers "
            f"against num_hidden_layers {total}. The config enumerates layers "
            "rather than counting them, so a mismatch means the enumeration is "
            "stale and neither number can be quoted.")
    return total, full, kda


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    a = ap.parse_args()

    paths = sorted(glob.glob(PATTERN))
    if not paths:
        raise SystemExit(f"ABORT: no checkpoint config under {PATTERN}")
    got = {p: shape(p) for p in paths}
    for p, s in got.items():
        print(f"  {os.path.basename(os.path.dirname(os.path.dirname(os.path.dirname(p))))}"
              f"   {s[0]} layers = {s[1]} MLA + {s[2]} linear")
    if len(set(got.values())) != 1:
        raise SystemExit(
            f"ABORT: the checkpoints disagree on the layer split: {set(got.values())}. "
            "The paper's arms are then not one architecture and no caption may "
            "say 'the model'.")
    total, full, kda = next(iter(got.values()))

    lines = ["% Generated by mexp/kimi/make_model_numbers.py from the checkpoint configs.",
             "% The hybrid split bounds every end-to-end ratio in the paper: VestigeKV",
             "% changes the MLA layers and nothing else.",
             f"\\newcommand{{\\hybridTotalLayers}}{{{total}}}",
             f"\\newcommand{{\\hybridMlaLayers}}{{{full}}}",
             f"\\newcommand{{\\hybridLinearLayers}}{{{kda}}}"]
    if a.emit:
        open(OUT, "w").write("\n".join(lines) + "\n")
        print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
