#!/usr/bin/env python3
"""Macros for the real-document continuation runs (litspeed).

Two ratios come out of these runs and they answer different questions. Reporting
either one alone misleads, in opposite directions.

**Decode ratio** (the method's speedup). Median ms/token from the server's own
gen-throughput lines, the same authority the serving figure uses, so both arms
are measured on the same plane -- the client streaming path penalises the faster
arm, which is why the client's number is not used here either.

**Wall ratio** (what the request sees). Total seconds for the job, which
includes prefill. These runs prefill a great deal and decode a little -- at 256k
it is four documents of 262144 tokens against 4x4096 generated -- so prefill
dominates the clock and the end-to-end gain is far smaller than the decode
speedup. That is not a defect of the measurement; it is what a prefill-heavy
request actually gets, and the paper says so.

    python mexp/kimi/make_litspeed_numbers.py [--out ~/vestigekv_paper/litspeed_numbers.tex]
"""
from __future__ import annotations

import argparse
import os
import collections
import re
import statistics
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESULTS = os.path.join(ROOT, "results", "kimi")

# context -> (tag used in the job id, macro suffix)
CELLS = [(65536, "64k", "SixtyFour"), (131072, "128k", "OneTwentyEight"),
         (262144, "256k", "TwoFiftySix")]
ARMS = {"baseline": "dense", "vestigekv": "vk"}


def decode_ms(arm, job):
    """Mean ms/token over the server's decode lines, TP0 only.

    Mean and not median, for the reason make_serving_speed_numbers.py gives at
    length: a median is a cost with the expensive steps removed, and only one
    arm here has expensive steps. VestigeKV closes a block and rebuilds an
    index every 4096 tokens; dense decode has no periodic work at all, so
    summarising the tail away discounts our own cost and nobody else's.

    Each line covers the same number of tokens, so the mean of the per-line
    ms/token IS the total time over the tokens decoded -- the span cancels.
    That equality is checked below rather than assumed.

    TP1 is excluded because the two ranks report separately and their rates
    differ; TP0 is the rank the serving figure reads."""
    p = os.path.join(RESULTS, f"server_{arm}_{job}.log")
    if not os.path.exists(p):
        return None
    v, ns = [], []
    for line in open(p, errors="replace"):
        if "TP0]" in line and "Decode batch" in line:
            m = re.search(r"gen throughput \(token/s\): ([0-9.]+)", line)
            n = re.search(r"#full token:\s*(\d+)", line)
            if m and float(m.group(1)) > 0:
                v.append(1000.0 / float(m.group(1)))
                ns.append(int(n.group(1)) if n else -1)
    if not v:
        return None
    # This log holds several requests, so a gap is either the steady-state
    # logging span or a jump into the next request. Keep the steady-state
    # lines: a line covering a whole new prefill is not a decode interval, and
    # averaging it in would price prefill into a decode number.
    gaps = collections.Counter(b - a for a, b in zip(ns, ns[1:]) if b > a)
    if not gaps:
        return None
    span, n_span = gaps.most_common(1)[0]
    if n_span < 0.9 * sum(gaps.values()):
        raise SystemExit(
            f"ABORT: {os.path.basename(p)} logs uneven decode spans "
            f"({span} covers only {n_span}/{sum(gaps.values())} intervals); an "
            "unweighted mean would overweight the short ones")
    keep = [ms for ms, a, b in zip(v[1:], ns, ns[1:]) if b - a == span]
    return sum(keep) / len(keep) if keep else None


def wall_s(arm, job):
    """Wall seconds and the run's shape, from the client's summary line."""
    p = os.path.join(RESULTS, f"continue_{arm}_{job}.log")
    if not os.path.exists(p):
        return None
    txt = open(p, errors="replace").read().replace("\r", "\n")
    m = None
    for m in re.finditer(r"continue_text in=(\d+) out=(\d+) n=(\d+) "
                         r"generated=(\d+) wall=(\d+)s", txt):
        pass
    if not m:
        return None
    return {"input_len": int(m.group(1)), "output_len": int(m.group(2)),
            "n": int(m.group(3)), "generated": int(m.group(4)),
            "wall": float(m.group(5))}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/litspeed_numbers.tex"))
    args = ap.parse_args()

    L = ["% Generated by mexp/kimi/make_litspeed_numbers.py from results/. "
         "Do not edit by hand."]
    ok = 0
    for ctx, tag, suf in CELLS:
        # The queue ids are the names on disk. These used to be the pre-rebase
        # job names (litspeed-64k-dense), which still exist beside the new ones
        # -- so the generator kept reading the retired tree's logs while the
        # re-run it was waiting for sat unused in the same directory.
        d_ms = decode_ms("baseline", f"litspeed{tag}-baseline")
        v_ms = decode_ms("vestigekv", f"litspeed{tag}-vestigekv")
        d_w = wall_s("baseline", f"litspeed{tag}-baseline")
        v_w = wall_s("vestigekv", f"litspeed{tag}-vestigekv")
        if not all((d_ms, v_ms, d_w, v_w)):
            L += [f"\\newcommand{{\\lit{suf}{k}}}{{\\PENDING}}"
                  for k in ("Decode", "Wall", "Dense", "Vk", "N")]
            continue
        ok += 1
        L.append(f"\\newcommand{{\\lit{suf}Decode}}{{{d_ms / v_ms:.3f}}}")
        L.append(f"\\newcommand{{\\lit{suf}Wall}}{{{d_w['wall'] / v_w['wall']:.3f}}}")
        L.append(f"\\newcommand{{\\lit{suf}Dense}}{{{d_ms:.3f}}}")
        L.append(f"\\newcommand{{\\lit{suf}Vk}}{{{v_ms:.3f}}}")
        L.append(f"\\newcommand{{\\lit{suf}N}}{{{d_w['n']}}}")
        # A request at this shape spends this fraction of its tokens on prefill;
        # it is why the wall ratio is so much smaller than the decode ratio, and
        # the paper quotes it rather than leaving the gap unexplained.
        pre = d_w["input_len"] * d_w["n"]
        L.append(f"\\newcommand{{\\lit{suf}PrefillShare}}"
                 f"{{{100 * pre / (pre + d_w['generated']):.1f}}}")
    L.append(f"\\newcommand{{\\litOutLen}}{{4096}}")
    open(args.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {args.out}: {len(L)} macros, {ok}/{len(CELLS)} cells measured")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
