#!/usr/bin/env python3
"""Macros for the KVzip head-to-head (harness needle, 8k, 24 trials per cell).

The review asked three times for a comparison against a method built for the
same quadrant -- training-free, query-independent, decided before any query --
because the paper's only empirical baselines were transplants of query-DEPENDENT
heuristics evaluated out of order, where they collapse by construction and say
nothing. KVzip is that method.

Both ranges are emitted and the paper prints both. Reporting only 32x/128x --
where this paper operates -- would repeat the exact criticism, because KVzip's
README claims 3-4x and 32x is an order of magnitude outside it. Reporting only
2x/4x/8x would hide where this paper actually runs. The pair is the honest unit.

    python mexp/kimi/make_kvzip_numbers.py [--out ~/vestigekv_paper/kvzip_numbers.tex]
"""
from __future__ import annotations

import argparse
import collections
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RUNS = ["results/harness_kvzip_inrange_8192.json",   # 2x, 4x, 8x
        "results/harness_kvzip_needle_8192.json",    # 32x, 128x
        "results/harness_selector_k16_8192.json"]    # the tier-2-deleted arm
# ratio -> macro suffix; ops -> macro infix.
#
# The tier-2-deleted arm reads `dig_r64`, NOT the `digk64` the first two runs
# carry. Both score the 64-dim branch; the k64 in the second name is the
# DETECTOR BANDWIDTH kappa=64, and the shipped constant is kappa=16, which is
# dig_r64's default. Printing digk64 understated the arm (0.75/0.25 against
# 0.92/0.83 at 32x/128x) and contradicted every kappa=16 number elsewhere in
# the paper. digk64's rows stay on disk and are ignored here by omission.
RATIO = {2: "Two", 4: "Four", 8: "Eight", 32: "ThirtyTwo", 128: "OTE"}
OPS = {"kvzip": "Kvzip", "twotier": "Vk", "dig_r64": "Sel",
       # the same selector at the OFF-SPEC bandwidth, emitted so the
       # bandwidth comparison in the appendix is generated from the
       # records rather than typed. The two arms differ in kappa and in
       # nothing else: same 24 needles, same seed, same checkpoint.
       "digk64": "SelKSixtyFour"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.expanduser(
        "~/vestigekv_paper/kvzip_numbers.tex"))
    args = ap.parse_args()

    agg = collections.defaultdict(list)
    for rel in RUNS:
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p):
            continue
        d = json.load(open(p))
        for r in (d["rows"] if isinstance(d, dict) and "rows" in d else d):
            if r.get("kind") != "needle":
                continue
            agg[(round(1 / r["rho"]), r["op"])].append(r["d"])

    L = ["% Generated by mexp/kimi/make_kvzip_numbers.py from results/. "
         "Do not edit by hand."]
    n_trials = set()
    for (ratio, op), v in sorted(agg.items()):
        if ratio not in RATIO or op not in OPS:
            continue
        n_trials.add(len(v))
        # A trial is intact when the answer-token NLL stays within 1 nat of
        # dense -- the same bar every other needle number in this paper uses.
        L.append(f"\\newcommand{{\\kvz{OPS[op]}{RATIO[ratio]}}}"
                 f"{{{sum(x < 1 for x in v) / len(v):.2f}}}")
    if len(n_trials) == 1:
        L.append(f"\\newcommand{{\\kvzTrials}}{{{n_trials.pop()}}}")
    open(args.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {args.out}: {len(L) - 1} macros over {len(agg)} cells")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
