#!/usr/bin/env python3
"""Which of the paper's numbers can a reader actually re-derive?

The Reproducibility statement used to say the archive holds "every run record
behind every number". It does not, and a reader who unzipped it would have
found that out before we did -- which is the cheapest possible way to lose a
reviewer's trust in every other number. This script measures what is true and
emits the two percentages the statement now prints, so the claim cannot drift
away from the archive again.

Two populations:

  regenerable   macros from a *_numbers.tex whose header says "% Generated by
                <script>". Those scripts read records that ship inside
                results/results.zip, so a reader runs the script and gets the
                same value.
  hand          macros from numbers.tex and serving_numbers.tex. Each carries
                its source in a trailing comment, but many of those sources
                are records from trees that no longer exist, and none of them
                are in the archive.

Only macros the paper actually cites are counted: numbers.tex defines far more
than it uses, and an uncited definition is not a claim.

    python mexp/tools/audit_provenance.py            # report
    python mexp/tools/audit_provenance.py --emit     # rewrite the percentages
    python mexp/tools/audit_provenance.py --check    # exit 1 if they drifted
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import zipfile

PAPER = os.path.expanduser("~/vestigekv_paper")
ARCHIVE = os.path.join(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))), "results", "results.zip")
SOURCES = ("main.tex", "sec_eng_serving.tex", "stationarity.tex")


def cited_names():
    used = set()
    for t in SOURCES:
        p = os.path.join(PAPER, t)
        if os.path.exists(p):
            used |= set(re.findall(r"\\([A-Za-z]+)\b", open(p).read()))
    return used


def shipped():
    have = set()
    if os.path.exists(ARCHIVE):
        have |= {os.path.basename(n) for n in zipfile.ZipFile(ARCHIVE).namelist()}
    for root, _, fs in os.walk(os.path.dirname(ARCHIVE)):
        have |= set(fs)
    return have


def survey():
    used, have = cited_names(), shipped()
    regen = hand = 0
    missing = {}
    for nf in sorted(glob.glob(os.path.join(PAPER, "*_numbers.tex"))
                     + [os.path.join(PAPER, "numbers.tex")]):
        text = open(nf).read()
        generated = text.splitlines()[0].startswith("% Generated by")
        for line in text.splitlines():
            m = re.match(r"\\newcommand\{\\([A-Za-z]+)\}\{.*?\}\s*(?:%\s*(.*))?$",
                         line.strip())
            # the two percentages this script emits are not measurements of
            # the paper, they are its report on itself
            if not m or m.group(1) not in used or m.group(1) in ("pctRegen", "pctHand"):
                continue
            name, prov = m.group(1), m.group(2) or ""
            if generated:
                regen += 1
                continue
            hand += 1
            if "RETIRED" in prov:
                continue
            for f in re.findall(r"[\w./-]+\.(?:json|txt|jsonl|csv|log)", prov):
                if os.path.basename(f) not in have:
                    missing.setdefault(os.path.basename(f), []).append(name)
    return regen, hand, missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    regen, hand, missing = survey()
    total = regen + hand
    pct = round(regen * 100 / total)
    print(f"cited macros: {total}   regenerable: {regen} ({pct}%)   "
          f"hand-maintained: {hand} ({100 - pct}%)")
    print(f"hand-maintained macros naming a record absent from the archive: "
          f"{sum(len(v) for v in missing.values())} over {len(missing)} files")
    for f, names in sorted(missing.items(), key=lambda kv: -len(kv[1]))[:10]:
        print(f"  {f:44s} {len(names):3d}  e.g. {names[:2]}")

    nums = os.path.join(PAPER, "numbers.tex")
    cur = re.search(r"\\newcommand\{\\pctRegen\}\{(\d+)\}", open(nums).read())
    if a.check:
        if not cur or int(cur.group(1)) != pct:
            raise SystemExit(
                f"ABORT: the paper prints {cur and cur.group(1)}% regenerable, "
                f"the archive supports {pct}%. Re-run with --emit.")
        print("check: the printed percentage matches the archive")
    if a.emit:
        s = open(nums).read()
        s = re.sub(r"\\newcommand\{\\pctRegen\}\{\d+\}",
                   f"\\\\newcommand{{\\\\pctRegen}}{{{pct}}}", s)
        s = re.sub(r"\\newcommand\{\\pctHand\}\{\d+\}",
                   f"\\\\newcommand{{\\\\pctHand}}{{{100 - pct}}}", s)
        open(nums, "w").write(s)
        print(f"emitted pctRegen={pct} pctHand={100 - pct}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
